// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mmult_accel_mmult_accel,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325t-fbg676-2L,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.080875,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=0,HLS_SYN_FF=17362,HLS_SYN_LUT=9847,HLS_VERSION=2024_2}" *)

module mmult_accel (
        ap_clk,
        ap_rst_n,
        A,
        B,
        C_i,
        C_o,
        C_o_ap_vld,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 27'd1;
parameter    ap_ST_fsm_state2 = 27'd2;
parameter    ap_ST_fsm_state3 = 27'd4;
parameter    ap_ST_fsm_state4 = 27'd8;
parameter    ap_ST_fsm_state5 = 27'd16;
parameter    ap_ST_fsm_state6 = 27'd32;
parameter    ap_ST_fsm_state7 = 27'd64;
parameter    ap_ST_fsm_state8 = 27'd128;
parameter    ap_ST_fsm_state9 = 27'd256;
parameter    ap_ST_fsm_state10 = 27'd512;
parameter    ap_ST_fsm_state11 = 27'd1024;
parameter    ap_ST_fsm_state12 = 27'd2048;
parameter    ap_ST_fsm_state13 = 27'd4096;
parameter    ap_ST_fsm_state14 = 27'd8192;
parameter    ap_ST_fsm_state15 = 27'd16384;
parameter    ap_ST_fsm_state16 = 27'd32768;
parameter    ap_ST_fsm_state17 = 27'd65536;
parameter    ap_ST_fsm_state18 = 27'd131072;
parameter    ap_ST_fsm_state19 = 27'd262144;
parameter    ap_ST_fsm_state20 = 27'd524288;
parameter    ap_ST_fsm_state21 = 27'd1048576;
parameter    ap_ST_fsm_state22 = 27'd2097152;
parameter    ap_ST_fsm_state23 = 27'd4194304;
parameter    ap_ST_fsm_state24 = 27'd8388608;
parameter    ap_ST_fsm_state25 = 27'd16777216;
parameter    ap_ST_fsm_state26 = 27'd33554432;
parameter    ap_ST_fsm_state27 = 27'd67108864;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] A;
input  [7:0] B;
input  [63:0] C_i;
output  [63:0] C_o;
output   C_o_ap_vld;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg[63:0] C_o;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [26:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] N;
wire   [31:0] K;
wire   [31:0] M;
wire   [31:0] update_A;
wire   [61:0] grp_fu_1233_p2;
reg   [61:0] reg_1239;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state16;
reg  signed [31:0] M_read_reg_1711;
reg   [31:0] K_read_reg_1716;
reg  signed [31:0] N_read_reg_1723;
wire  signed [32:0] sext_ln141_fu_1249_p1;
reg  signed [32:0] sext_ln141_reg_2017;
wire  signed [32:0] sext_ln141_1_fu_1253_p1;
reg  signed [32:0] sext_ln141_1_reg_2022;
wire  signed [32:0] sext_ln141_2_fu_1257_p1;
reg  signed [32:0] sext_ln141_2_reg_2028;
reg   [7:0] A_read_reg_2034;
reg   [7:0] B_read_reg_2039;
wire   [61:0] zext_ln141_1_fu_1275_p1;
reg   [61:0] zext_ln141_1_reg_2044;
wire   [31:0] add_ln142_fu_1296_p2;
reg   [31:0] add_ln142_reg_2053;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln142_fu_1306_p2;
reg   [0:0] icmp_ln142_reg_2058;
wire   [30:0] trunc_ln142_fu_1311_p1;
reg   [30:0] trunc_ln142_reg_2063;
wire  signed [31:0] current_block_M_A_fu_1328_p3;
reg   [31:0] current_block_M_A_reg_2068;
wire    ap_CS_fsm_state3;
wire   [30:0] trunc_ln142_1_fu_1336_p1;
reg   [30:0] trunc_ln142_1_reg_2074;
wire   [0:0] empty_39_fu_1340_p2;
reg   [0:0] empty_39_reg_2079;
wire   [61:0] zext_ln141_2_fu_1352_p1;
wire    ap_CS_fsm_state4;
wire  signed [32:0] current_block_M_A_cast_fu_1357_p1;
reg  signed [32:0] current_block_M_A_cast_reg_2089;
wire    ap_CS_fsm_state9;
wire   [31:0] add_ln168_fu_1369_p2;
reg   [31:0] add_ln168_reg_2097;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln168_fu_1379_p2;
reg   [0:0] icmp_ln168_reg_2102;
wire   [31:0] sub_ln168_fu_1392_p2;
reg   [31:0] sub_ln168_reg_2107;
wire  signed [31:0] current_block_M_fu_1406_p3;
reg   [31:0] current_block_M_reg_2112;
wire    ap_CS_fsm_state11;
wire   [30:0] smax4_fu_1423_p3;
reg   [30:0] smax4_reg_2120;
wire   [61:0] zext_ln167_1_fu_1431_p1;
wire    ap_CS_fsm_state12;
wire  signed [32:0] current_block_M_cast_fu_1435_p1;
reg  signed [32:0] current_block_M_cast_reg_2130;
wire    ap_CS_fsm_state17;
wire   [30:0] trunc_ln189_fu_1447_p1;
reg   [30:0] trunc_ln189_reg_2138;
wire    ap_CS_fsm_state18;
wire   [30:0] trunc_ln191_fu_1460_p1;
reg   [30:0] trunc_ln191_reg_2146;
wire    ap_CS_fsm_state19;
wire   [31:0] add_ln189_fu_1464_p2;
wire   [30:0] trunc_ln196_fu_1479_p1;
reg   [30:0] trunc_ln196_reg_2160;
wire    ap_CS_fsm_state20;
wire   [31:0] add_ln249_fu_1485_p2;
reg   [31:0] add_ln249_reg_2166;
wire   [2:0] add_ln305_fu_1673_p2;
reg   [2:0] add_ln305_reg_2318;
wire    ap_CS_fsm_state25;
wire   [1:0] trunc_ln305_fu_1679_p1;
reg   [1:0] trunc_ln305_reg_2323;
wire   [0:0] cmp248_fu_1693_p2;
reg   [0:0] cmp248_reg_2328;
wire   [31:0] add_ln191_fu_1698_p2;
reg    A_bram_ce0;
wire   [7:0] A_bram_q0;
reg    A_bram_ce1;
reg    A_bram_we1;
reg    B_bram_ce0;
wire   [7:0] B_bram_q0;
reg    B_bram_ce1;
reg    B_bram_we1;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_done;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_idle;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_ready;
wire   [14:0] grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_address1;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_ce1;
wire    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_we1;
wire   [7:0] grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_d1;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_done;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_idle;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_ready;
wire   [14:0] grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_address1;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_ce1;
wire    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_we1;
wire   [7:0] grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_d1;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_done;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_idle;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_ready;
wire   [14:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_address0;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_ce0;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out;
wire    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out_ap_vld;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_done;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_idle;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_ready;
wire   [14:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_address0;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_ce0;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out;
wire    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out_ap_vld;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_ap_start;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_ap_done;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_ap_idle;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_ap_ready;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out1;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out1_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out2;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out2_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out3;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out3_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out4;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out4_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out5;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out5_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out6;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out6_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out7;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out7_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out8;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out8_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out9;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out9_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out10;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out10_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out11;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out11_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out12;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out12_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out13;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out13_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_p_out14;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_p_out14_ap_vld;
wire   [63:0] grp_mmult_accel_Pipeline_compute_fu_1107_add22186_out;
wire    grp_mmult_accel_Pipeline_compute_fu_1107_add22186_out_ap_vld;
wire    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start;
wire    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_done;
wire    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_idle;
wire    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_ready;
wire   [63:0] grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o;
wire    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o_ap_vld;
reg   [31:0] j_block_reg_344;
wire   [0:0] icmp_ln189_fu_1442_p2;
reg   [31:0] i0_reg_355;
wire   [0:0] icmp_ln191_fu_1455_p2;
reg   [31:0] j0_reg_367;
wire   [0:0] icmp_ln305_fu_1667_p2;
reg   [63:0] localB_15_reg_379;
wire    ap_CS_fsm_state24;
reg   [63:0] localB_14_reg_391;
reg   [63:0] localB_13_reg_403;
reg   [63:0] localB_12_reg_415;
reg   [63:0] localB_11_reg_427;
reg   [63:0] localB_10_reg_439;
reg   [63:0] localB_9_reg_451;
reg   [63:0] localB_8_reg_463;
reg   [63:0] localB_7_reg_475;
reg   [63:0] localB_6_reg_487;
reg   [63:0] localB_5_reg_499;
reg   [63:0] localB_4_reg_511;
reg   [63:0] localB_3_reg_523;
reg   [63:0] localB_2_reg_535;
reg   [63:0] localB_1_reg_547;
reg   [63:0] localB_reg_559;
reg   [63:0] localA_15_reg_571;
reg   [63:0] localA_14_reg_583;
reg   [63:0] localA_13_reg_595;
reg   [63:0] localA_12_reg_607;
reg   [63:0] localA_11_reg_619;
reg   [63:0] localA_10_reg_631;
reg   [63:0] localA_9_reg_643;
reg   [63:0] localA_8_reg_655;
reg   [63:0] localA_7_reg_667;
reg   [63:0] localA_6_reg_679;
reg   [63:0] localA_5_reg_691;
reg   [63:0] localA_4_reg_703;
reg   [63:0] localA_3_reg_715;
reg   [63:0] localA_2_reg_727;
reg   [63:0] localA_1_reg_739;
reg   [63:0] localA_reg_751;
reg   [31:0] k0_reg_763;
reg   [63:0] localC_reg_774;
reg   [63:0] localC_1_reg_786;
reg   [63:0] localC_2_reg_798;
reg   [63:0] localC_3_reg_810;
reg   [63:0] localC_4_reg_822;
reg   [63:0] localC_5_reg_834;
reg   [63:0] localC_6_reg_846;
reg   [63:0] localC_7_reg_858;
reg   [63:0] localC_8_reg_870;
reg   [63:0] localC_9_reg_882;
reg   [63:0] localC_10_reg_894;
reg   [63:0] localC_11_reg_906;
reg   [63:0] localC_12_reg_918;
reg   [63:0] localC_13_reg_930;
reg   [63:0] localC_14_reg_942;
reg   [63:0] localC_15_reg_954;
reg   [2:0] ii_reg_966;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln249_fu_1474_p2;
reg    grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg;
reg    grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg;
reg    grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg;
wire    ap_CS_fsm_state21;
reg    grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg;
reg    grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
reg    grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg;
wire    ap_CS_fsm_state26;
reg   [63:0] C_o_reg;
reg   [31:0] start_row_A_fu_110;
wire   [0:0] icmp_ln167_fu_1364_p2;
reg   [30:0] grp_fu_1233_p0;
reg   [30:0] grp_fu_1233_p1;
wire  signed [31:0] empty_fu_1245_p0;
wire  signed [31:0] sext_ln141_fu_1249_p0;
wire  signed [31:0] sext_ln141_1_fu_1253_p0;
wire  signed [31:0] sext_ln141_2_fu_1257_p0;
wire  signed [31:0] empty_38_fu_1261_p0;
wire   [0:0] empty_38_fu_1261_p2;
wire   [30:0] empty_fu_1245_p1;
wire   [30:0] smax1_fu_1267_p3;
wire   [32:0] zext_ln141_fu_1287_p1;
wire   [32:0] zext_ln142_fu_1302_p1;
wire   [31:0] zext_ln142_1_fu_1320_p1;
wire   [0:0] xor_ln142_fu_1315_p2;
wire   [31:0] sub_ln142_fu_1323_p2;
wire   [30:0] smax_fu_1346_p3;
wire   [32:0] zext_ln167_fu_1360_p1;
wire   [32:0] zext_ln168_fu_1375_p1;
wire   [30:0] trunc_ln168_fu_1384_p1;
wire   [31:0] zext_ln168_1_fu_1388_p1;
wire   [0:0] xor_ln168_fu_1401_p2;
wire   [0:0] empty_40_fu_1417_p2;
wire   [30:0] trunc_ln168_1_fu_1413_p1;
wire   [32:0] zext_ln189_fu_1438_p1;
wire   [32:0] zext_ln191_fu_1451_p1;
wire   [32:0] zext_ln196_fu_1470_p1;
wire   [31:0] zext_ln305_fu_1683_p1;
wire   [31:0] empty_41_fu_1687_p2;
wire   [0:0] icmp_ln141_fu_1291_p2;
reg   [26:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_block_state21_on_subcall_done;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 27'd1;
#0 grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg = 1'b0;
#0 grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg = 1'b0;
#0 grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg = 1'b0;
#0 grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg = 1'b0;
#0 grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg = 1'b0;
#0 grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg = 1'b0;
#0 start_row_A_fu_110 = 32'd0;
end

mmult_accel_A_bram_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 24576 ),
    .AddressWidth( 15 ))
A_bram_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_address0),
    .ce0(A_bram_ce0),
    .q0(A_bram_q0),
    .address1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_address1),
    .ce1(A_bram_ce1),
    .we1(A_bram_we1),
    .d1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_d1)
);

mmult_accel_A_bram_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 24576 ),
    .AddressWidth( 15 ))
B_bram_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_address0),
    .ce0(B_bram_ce0),
    .q0(B_bram_q0),
    .address1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_address1),
    .ce1(B_bram_ce1),
    .we1(B_bram_we1),
    .d1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_d1)
);

mmult_accel_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1 grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_ready),
    .K(K_read_reg_1716),
    .mul_ln141(reg_1239),
    .A_bram_address1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_address1),
    .A_bram_ce1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_ce1),
    .A_bram_we1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_we1),
    .A_bram_d1(grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_d1),
    .A_load(A_read_reg_2034)
);

mmult_accel_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2 grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_ready),
    .current_block_M(current_block_M_reg_2112),
    .mul_ln167(reg_1239),
    .B_bram_address1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_address1),
    .B_bram_ce1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_ce1),
    .B_bram_we1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_we1),
    .B_bram_d1(grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_d1),
    .B_load(B_read_reg_2039)
);

mmult_accel_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6 grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_ready),
    .localA_15(localA_15_reg_571),
    .localA_14(localA_14_reg_583),
    .localA_13(localA_13_reg_595),
    .localA_12(localA_12_reg_607),
    .localA_11(localA_11_reg_619),
    .localA_10(localA_10_reg_631),
    .localA_9(localA_9_reg_643),
    .localA_8(localA_8_reg_655),
    .localA_7(localA_7_reg_667),
    .localA_6(localA_6_reg_679),
    .localA_5(localA_5_reg_691),
    .localA_4(localA_4_reg_703),
    .localA_3(localA_3_reg_715),
    .localA_2(localA_2_reg_727),
    .localA_1(localA_1_reg_739),
    .localA(localA_reg_751),
    .i0(trunc_ln189_reg_2138),
    .current_block_M_A(current_block_M_A_reg_2068),
    .k0(trunc_ln196_reg_2160),
    .A_bram_address0(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_address0),
    .A_bram_ce0(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_ce0),
    .A_bram_q0(A_bram_q0),
    .K(K_read_reg_1716),
    .localA_31_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out),
    .localA_31_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out_ap_vld),
    .localA_30_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out),
    .localA_30_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out_ap_vld),
    .localA_29_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out),
    .localA_29_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out_ap_vld),
    .localA_28_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out),
    .localA_28_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out_ap_vld),
    .localA_27_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out),
    .localA_27_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out_ap_vld),
    .localA_26_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out),
    .localA_26_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out_ap_vld),
    .localA_25_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out),
    .localA_25_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out_ap_vld),
    .localA_24_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out),
    .localA_24_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out_ap_vld),
    .localA_23_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out),
    .localA_23_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out_ap_vld),
    .localA_22_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out),
    .localA_22_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out_ap_vld),
    .localA_21_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out),
    .localA_21_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out_ap_vld),
    .localA_20_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out),
    .localA_20_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out_ap_vld),
    .localA_19_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out),
    .localA_19_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out_ap_vld),
    .localA_18_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out),
    .localA_18_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out_ap_vld),
    .localA_17_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out),
    .localA_17_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out_ap_vld),
    .localA_16_out(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out),
    .localA_16_out_ap_vld(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out_ap_vld)
);

mmult_accel_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7 grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_ready),
    .localB_15(localB_15_reg_379),
    .localB_14(localB_14_reg_391),
    .localB_13(localB_13_reg_403),
    .localB_12(localB_12_reg_415),
    .localB_11(localB_11_reg_427),
    .localB_10(localB_10_reg_439),
    .localB_9(localB_9_reg_451),
    .localB_8(localB_8_reg_463),
    .localB_7(localB_7_reg_475),
    .localB_6(localB_6_reg_487),
    .localB_5(localB_5_reg_499),
    .localB_4(localB_4_reg_511),
    .localB_3(localB_3_reg_523),
    .localB_2(localB_2_reg_535),
    .localB_1(localB_1_reg_547),
    .localB(localB_reg_559),
    .k0(trunc_ln196_reg_2160),
    .K(K_read_reg_1716),
    .j0(trunc_ln191_reg_2146),
    .B_bram_address0(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_address0),
    .B_bram_ce0(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_ce0),
    .B_bram_q0(B_bram_q0),
    .current_block_M(current_block_M_reg_2112),
    .localB_31_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out),
    .localB_31_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out_ap_vld),
    .localB_30_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out),
    .localB_30_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out_ap_vld),
    .localB_29_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out),
    .localB_29_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out_ap_vld),
    .localB_28_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out),
    .localB_28_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out_ap_vld),
    .localB_27_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out),
    .localB_27_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out_ap_vld),
    .localB_26_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out),
    .localB_26_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out_ap_vld),
    .localB_25_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out),
    .localB_25_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out_ap_vld),
    .localB_24_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out),
    .localB_24_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out_ap_vld),
    .localB_23_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out),
    .localB_23_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out_ap_vld),
    .localB_22_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out),
    .localB_22_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out_ap_vld),
    .localB_21_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out),
    .localB_21_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out_ap_vld),
    .localB_20_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out),
    .localB_20_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out_ap_vld),
    .localB_19_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out),
    .localB_19_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out_ap_vld),
    .localB_18_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out),
    .localB_18_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out_ap_vld),
    .localB_17_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out),
    .localB_17_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out_ap_vld),
    .localB_16_out(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out),
    .localB_16_out_ap_vld(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out_ap_vld)
);

mmult_accel_mmult_accel_Pipeline_compute grp_mmult_accel_Pipeline_compute_fu_1107(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_compute_fu_1107_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_compute_fu_1107_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_compute_fu_1107_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_compute_fu_1107_ap_ready),
    .localC(localC_reg_774),
    .localC_1(localC_1_reg_786),
    .localC_2(localC_2_reg_798),
    .localC_3(localC_3_reg_810),
    .localC_4(localC_4_reg_822),
    .localC_5(localC_5_reg_834),
    .localC_6(localC_6_reg_846),
    .localC_7(localC_7_reg_858),
    .localC_8(localC_8_reg_870),
    .localC_9(localC_9_reg_882),
    .localC_10(localC_10_reg_894),
    .localC_11(localC_11_reg_906),
    .localC_12(localC_12_reg_918),
    .localC_13(localC_13_reg_930),
    .localC_14(localC_14_reg_942),
    .localC_15(localC_15_reg_954),
    .localA_16_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out),
    .localA_17_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out),
    .localA_18_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out),
    .localA_19_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out),
    .localB_16_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out),
    .localB_20_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out),
    .localB_24_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out),
    .localB_28_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out),
    .localB_17_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out),
    .localB_21_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out),
    .localB_25_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out),
    .localB_29_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out),
    .localB_18_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out),
    .localB_22_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out),
    .localB_26_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out),
    .localB_30_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out),
    .localB_19_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out),
    .localB_23_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out),
    .localB_27_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out),
    .localB_31_reload(grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out),
    .localA_20_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out),
    .localA_21_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out),
    .localA_22_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out),
    .localA_23_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out),
    .localA_24_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out),
    .localA_25_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out),
    .localA_26_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out),
    .localA_27_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out),
    .localA_28_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out),
    .localA_29_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out),
    .localA_30_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out),
    .localA_31_reload(grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out),
    .p_out(grp_mmult_accel_Pipeline_compute_fu_1107_p_out),
    .p_out_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out_ap_vld),
    .p_out1(grp_mmult_accel_Pipeline_compute_fu_1107_p_out1),
    .p_out1_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out1_ap_vld),
    .p_out2(grp_mmult_accel_Pipeline_compute_fu_1107_p_out2),
    .p_out2_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out2_ap_vld),
    .p_out3(grp_mmult_accel_Pipeline_compute_fu_1107_p_out3),
    .p_out3_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out3_ap_vld),
    .p_out4(grp_mmult_accel_Pipeline_compute_fu_1107_p_out4),
    .p_out4_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out4_ap_vld),
    .p_out5(grp_mmult_accel_Pipeline_compute_fu_1107_p_out5),
    .p_out5_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out5_ap_vld),
    .p_out6(grp_mmult_accel_Pipeline_compute_fu_1107_p_out6),
    .p_out6_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out6_ap_vld),
    .p_out7(grp_mmult_accel_Pipeline_compute_fu_1107_p_out7),
    .p_out7_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out7_ap_vld),
    .p_out8(grp_mmult_accel_Pipeline_compute_fu_1107_p_out8),
    .p_out8_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out8_ap_vld),
    .p_out9(grp_mmult_accel_Pipeline_compute_fu_1107_p_out9),
    .p_out9_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out9_ap_vld),
    .p_out10(grp_mmult_accel_Pipeline_compute_fu_1107_p_out10),
    .p_out10_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out10_ap_vld),
    .p_out11(grp_mmult_accel_Pipeline_compute_fu_1107_p_out11),
    .p_out11_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out11_ap_vld),
    .p_out12(grp_mmult_accel_Pipeline_compute_fu_1107_p_out12),
    .p_out12_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out12_ap_vld),
    .p_out13(grp_mmult_accel_Pipeline_compute_fu_1107_p_out13),
    .p_out13_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out13_ap_vld),
    .p_out14(grp_mmult_accel_Pipeline_compute_fu_1107_p_out14),
    .p_out14_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_p_out14_ap_vld),
    .add22186_out(grp_mmult_accel_Pipeline_compute_fu_1107_add22186_out),
    .add22186_out_ap_vld(grp_mmult_accel_Pipeline_compute_fu_1107_add22186_out_ap_vld)
);

mmult_accel_mmult_accel_Pipeline_VITIS_LOOP_306_10 grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start),
    .ap_done(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_done),
    .ap_idle(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_idle),
    .ap_ready(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_ready),
    .j0(trunc_ln191_reg_2146),
    .current_block_M(current_block_M_reg_2112),
    .cmp248(cmp248_reg_2328),
    .localC_15(localC_15_reg_954),
    .localC_14(localC_14_reg_942),
    .localC_13(localC_13_reg_930),
    .localC_12(localC_12_reg_918),
    .localC_11(localC_11_reg_906),
    .localC_10(localC_10_reg_894),
    .localC_9(localC_9_reg_882),
    .localC_8(localC_8_reg_870),
    .localC_7(localC_7_reg_858),
    .localC_6(localC_6_reg_846),
    .localC_5(localC_5_reg_834),
    .localC_4(localC_4_reg_822),
    .localC_3(localC_3_reg_810),
    .localC_2(localC_2_reg_798),
    .localC_1(localC_1_reg_786),
    .localC(localC_reg_774),
    .C_i(C_i),
    .C_o(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o),
    .C_o_ap_vld(grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o_ap_vld),
    .ii_1(trunc_ln305_reg_2323)
);

mmult_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .N(N),
    .K(K),
    .M(M),
    .update_A(update_A),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

mmult_accel_mul_31ns_31ns_62_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 62 ))
mul_31ns_31ns_62_5_1_U199(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1233_p0),
    .din1(grp_fu_1233_p1),
    .ce(1'b1),
    .dout(grp_fu_1233_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state26)) begin
            grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_compute_fu_1107_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln249_fu_1474_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln249_fu_1474_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg <= 1'b1;
        end else if ((grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_ready == 1'b1)) begin
            grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        i0_reg_355 <= 32'd0;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        i0_reg_355 <= add_ln189_fu_1464_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln249_fu_1474_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        ii_reg_966 <= 3'd0;
    end else if (((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        ii_reg_966 <= add_ln305_reg_2318;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln305_fu_1667_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        j0_reg_367 <= add_ln191_fu_1698_p2;
    end else if (((icmp_ln189_fu_1442_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        j0_reg_367 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        j_block_reg_344 <= 32'd0;
    end else if (((icmp_ln189_fu_1442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
        j_block_reg_344 <= add_ln168_reg_2097;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        k0_reg_763 <= add_ln249_reg_2166;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        k0_reg_763 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_10_reg_631 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_26_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_10_reg_631 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_11_reg_619 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_27_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_11_reg_619 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_12_reg_607 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_28_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_12_reg_607 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_13_reg_595 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_29_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_13_reg_595 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_14_reg_583 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_30_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_14_reg_583 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_15_reg_571 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_31_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_15_reg_571 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_1_reg_739 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_17_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_1_reg_739 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_2_reg_727 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_18_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_2_reg_727 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_3_reg_715 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_19_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_3_reg_715 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_4_reg_703 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_20_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_4_reg_703 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_5_reg_691 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_21_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_5_reg_691 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_6_reg_679 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_22_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_6_reg_679 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_7_reg_667 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_23_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_7_reg_667 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_8_reg_655 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_24_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_8_reg_655 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_9_reg_643 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_25_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_9_reg_643 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localA_reg_751 <= grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_localA_16_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localA_reg_751 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_10_reg_439 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_26_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_10_reg_439 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_11_reg_427 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_27_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_11_reg_427 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_12_reg_415 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_28_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_12_reg_415 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_13_reg_403 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_29_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_13_reg_403 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_14_reg_391 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_30_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_14_reg_391 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_15_reg_379 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_31_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_15_reg_379 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_1_reg_547 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_17_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_1_reg_547 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_2_reg_535 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_18_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_2_reg_535 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_3_reg_523 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_19_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_3_reg_523 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_4_reg_511 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_20_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_4_reg_511 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_5_reg_499 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_21_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_5_reg_499 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_6_reg_487 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_22_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_6_reg_487 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_7_reg_475 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_23_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_7_reg_475 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_8_reg_463 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_24_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_8_reg_463 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_9_reg_451 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_25_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_9_reg_451 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localB_reg_559 <= grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_localB_16_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localB_reg_559 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_10_reg_894 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out10;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_10_reg_894 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_11_reg_906 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out11;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_11_reg_906 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_12_reg_918 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out12;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_12_reg_918 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_13_reg_930 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out13;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_13_reg_930 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_14_reg_942 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out14;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_14_reg_942 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_15_reg_954 <= grp_mmult_accel_Pipeline_compute_fu_1107_add22186_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_15_reg_954 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_1_reg_786 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out1;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_1_reg_786 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_2_reg_798 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out2;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_2_reg_798 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_3_reg_810 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out3;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_3_reg_810 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_4_reg_822 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out4;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_4_reg_822 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_5_reg_834 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out5;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_5_reg_834 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_6_reg_846 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out6;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_6_reg_846 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_7_reg_858 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out7;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_7_reg_858 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_8_reg_870 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out8;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_8_reg_870 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_9_reg_882 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out9;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_9_reg_882 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        localC_reg_774 <= grp_mmult_accel_Pipeline_compute_fu_1107_p_out;
    end else if (((icmp_ln191_fu_1455_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        localC_reg_774 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        start_row_A_fu_110 <= 32'd0;
    end else if (((icmp_ln167_fu_1364_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        start_row_A_fu_110 <= add_ln142_reg_2053;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        A_read_reg_2034 <= A;
        B_read_reg_2039 <= B;
        K_read_reg_1716 <= K;
        M_read_reg_1711 <= M;
        N_read_reg_1723 <= N;
        sext_ln141_1_reg_2022 <= sext_ln141_1_fu_1253_p1;
        sext_ln141_2_reg_2028 <= sext_ln141_2_fu_1257_p1;
        sext_ln141_reg_2017 <= sext_ln141_fu_1249_p1;
        zext_ln141_1_reg_2044[30 : 0] <= zext_ln141_1_fu_1275_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        C_o_reg <= grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln142_reg_2053 <= add_ln142_fu_1296_p2;
        icmp_ln142_reg_2058 <= icmp_ln142_fu_1306_p2;
        trunc_ln142_reg_2063 <= trunc_ln142_fu_1311_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln168_reg_2097 <= add_ln168_fu_1369_p2;
        icmp_ln168_reg_2102 <= icmp_ln168_fu_1379_p2;
        sub_ln168_reg_2107 <= sub_ln168_fu_1392_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln249_reg_2166 <= add_ln249_fu_1485_p2;
        trunc_ln196_reg_2160 <= trunc_ln196_fu_1479_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        add_ln305_reg_2318 <= add_ln305_fu_1673_p2;
        cmp248_reg_2328 <= cmp248_fu_1693_p2;
        trunc_ln305_reg_2323 <= trunc_ln305_fu_1679_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        current_block_M_A_cast_reg_2089 <= current_block_M_A_cast_fu_1357_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        current_block_M_A_reg_2068 <= current_block_M_A_fu_1328_p3;
        empty_39_reg_2079 <= empty_39_fu_1340_p2;
        trunc_ln142_1_reg_2074 <= trunc_ln142_1_fu_1336_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        current_block_M_cast_reg_2130 <= current_block_M_cast_fu_1435_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        current_block_M_reg_2112 <= current_block_M_fu_1406_p3;
        smax4_reg_2120 <= smax4_fu_1423_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_1239 <= grp_fu_1233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        trunc_ln189_reg_2138 <= trunc_ln189_fu_1447_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        trunc_ln191_reg_2146 <= trunc_ln191_fu_1460_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        A_bram_ce0 = grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_A_bram_ce0;
    end else begin
        A_bram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        A_bram_ce1 = grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_ce1;
    end else begin
        A_bram_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        A_bram_we1 = grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_A_bram_we1;
    end else begin
        A_bram_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        B_bram_ce0 = grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_B_bram_ce0;
    end else begin
        B_bram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        B_bram_ce1 = grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_ce1;
    end else begin
        B_bram_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        B_bram_we1 = grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_B_bram_we1;
    end else begin
        B_bram_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        C_o = grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o;
    end else begin
        C_o = C_o_reg;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state21_on_subcall_done)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_mmult_accel_Pipeline_compute_fu_1107_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln141_fu_1291_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln141_fu_1291_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_1233_p0 = zext_ln141_1_reg_2044;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_1233_p0 = zext_ln141_2_fu_1352_p1;
    end else begin
        grp_fu_1233_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_1233_p1 = zext_ln167_1_fu_1431_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_1233_p1 = zext_ln141_1_reg_2044;
    end else begin
        grp_fu_1233_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln141_fu_1291_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln167_fu_1364_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln189_fu_1442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln191_fu_1455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln249_fu_1474_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (1'b0 == ap_block_state21_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_mmult_accel_Pipeline_compute_fu_1107_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln305_fu_1667_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_o_ap_vld = grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_C_o_ap_vld;

assign add_ln142_fu_1296_p2 = (start_row_A_fu_110 + 32'd32);

assign add_ln168_fu_1369_p2 = (j_block_reg_344 + 32'd32);

assign add_ln189_fu_1464_p2 = (i0_reg_355 + 32'd4);

assign add_ln191_fu_1698_p2 = (j0_reg_367 + 32'd4);

assign add_ln249_fu_1485_p2 = (k0_reg_763 + 32'd4);

assign add_ln305_fu_1673_p2 = (ii_reg_966 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state21_on_subcall_done = ((grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_done == 1'b0) | (grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp248_fu_1693_p2 = (($signed(empty_41_fu_1687_p2) < $signed(N_read_reg_1723)) ? 1'b1 : 1'b0);

assign current_block_M_A_cast_fu_1357_p1 = $signed(current_block_M_A_reg_2068);

assign current_block_M_A_fu_1328_p3 = ((xor_ln142_fu_1315_p2[0:0] == 1'b1) ? 32'd32 : sub_ln142_fu_1323_p2);

assign current_block_M_cast_fu_1435_p1 = $signed(current_block_M_reg_2112);

assign current_block_M_fu_1406_p3 = ((xor_ln168_fu_1401_p2[0:0] == 1'b1) ? 32'd32 : sub_ln168_reg_2107);

assign empty_38_fu_1261_p0 = K;

assign empty_38_fu_1261_p2 = (($signed(empty_38_fu_1261_p0) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_39_fu_1340_p2 = (($signed(current_block_M_A_fu_1328_p3) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_40_fu_1417_p2 = (($signed(current_block_M_fu_1406_p3) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_41_fu_1687_p2 = (zext_ln305_fu_1683_p1 + i0_reg_355);

assign empty_fu_1245_p0 = K;

assign empty_fu_1245_p1 = empty_fu_1245_p0[30:0];

assign grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start = grp_mmult_accel_Pipeline_VITIS_LOOP_306_10_fu_1191_ap_start_reg;

assign grp_mmult_accel_Pipeline_compute_fu_1107_ap_start = grp_mmult_accel_Pipeline_compute_fu_1107_ap_start_reg;

assign grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start = grp_mmult_accel_Pipeline_copy_A_tile_VITIS_LOOP_154_1_fu_977_ap_start_reg;

assign grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start = grp_mmult_accel_Pipeline_copy_B_block_VITIS_LOOP_177_2_fu_985_ap_start_reg;

assign grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start = grp_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6_fu_993_ap_start_reg;

assign grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start = grp_mmult_accel_Pipeline_loadB_VITIS_LOOP_269_7_fu_1050_ap_start_reg;

assign icmp_ln141_fu_1291_p2 = (($signed(zext_ln141_fu_1287_p1) < $signed(sext_ln141_2_reg_2028)) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_1306_p2 = (($signed(sext_ln141_2_reg_2028) < $signed(zext_ln142_fu_1302_p1)) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_1364_p2 = (($signed(zext_ln167_fu_1360_p1) < $signed(sext_ln141_1_reg_2022)) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_1379_p2 = (($signed(sext_ln141_1_reg_2022) < $signed(zext_ln168_fu_1375_p1)) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_1442_p2 = (($signed(zext_ln189_fu_1438_p1) < $signed(current_block_M_A_cast_reg_2089)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_1455_p2 = (($signed(zext_ln191_fu_1451_p1) < $signed(current_block_M_cast_reg_2130)) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_1474_p2 = (($signed(zext_ln196_fu_1470_p1) < $signed(sext_ln141_reg_2017)) ? 1'b1 : 1'b0);

assign icmp_ln305_fu_1667_p2 = ((ii_reg_966 == 3'd4) ? 1'b1 : 1'b0);

assign sext_ln141_1_fu_1253_p0 = M;

assign sext_ln141_1_fu_1253_p1 = sext_ln141_1_fu_1253_p0;

assign sext_ln141_2_fu_1257_p0 = N;

assign sext_ln141_2_fu_1257_p1 = sext_ln141_2_fu_1257_p0;

assign sext_ln141_fu_1249_p0 = K;

assign sext_ln141_fu_1249_p1 = sext_ln141_fu_1249_p0;

assign smax1_fu_1267_p3 = ((empty_38_fu_1261_p2[0:0] == 1'b1) ? empty_fu_1245_p1 : 31'd0);

assign smax4_fu_1423_p3 = ((empty_40_fu_1417_p2[0:0] == 1'b1) ? trunc_ln168_1_fu_1413_p1 : 31'd0);

assign smax_fu_1346_p3 = ((empty_39_reg_2079[0:0] == 1'b1) ? trunc_ln142_1_reg_2074 : 31'd0);

assign sub_ln142_fu_1323_p2 = ($signed(N_read_reg_1723) - $signed(zext_ln142_1_fu_1320_p1));

assign sub_ln168_fu_1392_p2 = ($signed(M_read_reg_1711) - $signed(zext_ln168_1_fu_1388_p1));

assign trunc_ln142_1_fu_1336_p1 = current_block_M_A_fu_1328_p3[30:0];

assign trunc_ln142_fu_1311_p1 = start_row_A_fu_110[30:0];

assign trunc_ln168_1_fu_1413_p1 = current_block_M_fu_1406_p3[30:0];

assign trunc_ln168_fu_1384_p1 = j_block_reg_344[30:0];

assign trunc_ln189_fu_1447_p1 = i0_reg_355[30:0];

assign trunc_ln191_fu_1460_p1 = j0_reg_367[30:0];

assign trunc_ln196_fu_1479_p1 = k0_reg_763[30:0];

assign trunc_ln305_fu_1679_p1 = ii_reg_966[1:0];

assign xor_ln142_fu_1315_p2 = (icmp_ln142_reg_2058 ^ 1'd1);

assign xor_ln168_fu_1401_p2 = (icmp_ln168_reg_2102 ^ 1'd1);

assign zext_ln141_1_fu_1275_p1 = smax1_fu_1267_p3;

assign zext_ln141_2_fu_1352_p1 = smax_fu_1346_p3;

assign zext_ln141_fu_1287_p1 = start_row_A_fu_110;

assign zext_ln142_1_fu_1320_p1 = trunc_ln142_reg_2063;

assign zext_ln142_fu_1302_p1 = add_ln142_fu_1296_p2;

assign zext_ln167_1_fu_1431_p1 = smax4_reg_2120;

assign zext_ln167_fu_1360_p1 = j_block_reg_344;

assign zext_ln168_1_fu_1388_p1 = trunc_ln168_fu_1384_p1;

assign zext_ln168_fu_1375_p1 = add_ln168_fu_1369_p2;

assign zext_ln189_fu_1438_p1 = i0_reg_355;

assign zext_ln191_fu_1451_p1 = j0_reg_367;

assign zext_ln196_fu_1470_p1 = k0_reg_763;

assign zext_ln305_fu_1683_p1 = ii_reg_966;

always @ (posedge ap_clk) begin
    zext_ln141_1_reg_2044[61:31] <= 31'b0000000000000000000000000000000;
end

endmodule //mmult_accel
