// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dequantize_nf4_q2_6_dequantize_nf4_q2_6_Pipeline_VITIS_LOOP_87_51 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weights_buf_32_address0,
        weights_buf_32_ce0,
        weights_buf_32_q0,
        indvars_iv35_udiv_cast,
        weights_buf_33_address0,
        weights_buf_33_ce0,
        weights_buf_33_q0,
        weights_buf_34_address0,
        weights_buf_34_ce0,
        weights_buf_34_q0,
        weights_buf_35_address0,
        weights_buf_35_ce0,
        weights_buf_35_q0,
        weights_buf_36_address0,
        weights_buf_36_ce0,
        weights_buf_36_q0,
        weights_buf_37_address0,
        weights_buf_37_ce0,
        weights_buf_37_q0,
        weights_buf_38_address0,
        weights_buf_38_ce0,
        weights_buf_38_q0,
        weights_buf_39_address0,
        weights_buf_39_ce0,
        weights_buf_39_q0,
        weights_buf_40_address0,
        weights_buf_40_ce0,
        weights_buf_40_q0,
        weights_buf_41_address0,
        weights_buf_41_ce0,
        weights_buf_41_q0,
        weights_buf_42_address0,
        weights_buf_42_ce0,
        weights_buf_42_q0,
        weights_buf_43_address0,
        weights_buf_43_ce0,
        weights_buf_43_q0,
        weights_buf_44_address0,
        weights_buf_44_ce0,
        weights_buf_44_q0,
        weights_buf_45_address0,
        weights_buf_45_ce0,
        weights_buf_45_q0,
        weights_buf_46_address0,
        weights_buf_46_ce0,
        weights_buf_46_q0,
        weights_buf_47_address0,
        weights_buf_47_ce0,
        weights_buf_47_q0,
        weights_buf_48_address0,
        weights_buf_48_ce0,
        weights_buf_48_q0,
        weights_buf_49_address0,
        weights_buf_49_ce0,
        weights_buf_49_q0,
        weights_buf_50_address0,
        weights_buf_50_ce0,
        weights_buf_50_q0,
        weights_buf_51_address0,
        weights_buf_51_ce0,
        weights_buf_51_q0,
        weights_buf_52_address0,
        weights_buf_52_ce0,
        weights_buf_52_q0,
        weights_buf_53_address0,
        weights_buf_53_ce0,
        weights_buf_53_q0,
        weights_buf_54_address0,
        weights_buf_54_ce0,
        weights_buf_54_q0,
        weights_buf_55_address0,
        weights_buf_55_ce0,
        weights_buf_55_q0,
        weights_buf_56_address0,
        weights_buf_56_ce0,
        weights_buf_56_q0,
        weights_buf_57_address0,
        weights_buf_57_ce0,
        weights_buf_57_q0,
        weights_buf_58_address0,
        weights_buf_58_ce0,
        weights_buf_58_q0,
        weights_buf_59_address0,
        weights_buf_59_ce0,
        weights_buf_59_q0,
        weights_buf_60_address0,
        weights_buf_60_ce0,
        weights_buf_60_q0,
        weights_buf_61_address0,
        weights_buf_61_ce0,
        weights_buf_61_q0,
        weights_buf_62_address0,
        weights_buf_62_ce0,
        weights_buf_62_q0,
        weights_buf_63_address0,
        weights_buf_63_ce0,
        weights_buf_63_q0,
        out_index,
        sext_ln58,
        lookup_values_address0,
        lookup_values_ce0,
        lookup_values_q0,
        sext_ln100_3,
        DQ_bram,
        DQ_bram_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] weights_buf_32_address0;
output   weights_buf_32_ce0;
input  [7:0] weights_buf_32_q0;
input  [6:0] indvars_iv35_udiv_cast;
output  [6:0] weights_buf_33_address0;
output   weights_buf_33_ce0;
input  [7:0] weights_buf_33_q0;
output  [6:0] weights_buf_34_address0;
output   weights_buf_34_ce0;
input  [7:0] weights_buf_34_q0;
output  [6:0] weights_buf_35_address0;
output   weights_buf_35_ce0;
input  [7:0] weights_buf_35_q0;
output  [6:0] weights_buf_36_address0;
output   weights_buf_36_ce0;
input  [7:0] weights_buf_36_q0;
output  [6:0] weights_buf_37_address0;
output   weights_buf_37_ce0;
input  [7:0] weights_buf_37_q0;
output  [6:0] weights_buf_38_address0;
output   weights_buf_38_ce0;
input  [7:0] weights_buf_38_q0;
output  [6:0] weights_buf_39_address0;
output   weights_buf_39_ce0;
input  [7:0] weights_buf_39_q0;
output  [6:0] weights_buf_40_address0;
output   weights_buf_40_ce0;
input  [7:0] weights_buf_40_q0;
output  [6:0] weights_buf_41_address0;
output   weights_buf_41_ce0;
input  [7:0] weights_buf_41_q0;
output  [6:0] weights_buf_42_address0;
output   weights_buf_42_ce0;
input  [7:0] weights_buf_42_q0;
output  [6:0] weights_buf_43_address0;
output   weights_buf_43_ce0;
input  [7:0] weights_buf_43_q0;
output  [6:0] weights_buf_44_address0;
output   weights_buf_44_ce0;
input  [7:0] weights_buf_44_q0;
output  [6:0] weights_buf_45_address0;
output   weights_buf_45_ce0;
input  [7:0] weights_buf_45_q0;
output  [6:0] weights_buf_46_address0;
output   weights_buf_46_ce0;
input  [7:0] weights_buf_46_q0;
output  [6:0] weights_buf_47_address0;
output   weights_buf_47_ce0;
input  [7:0] weights_buf_47_q0;
output  [6:0] weights_buf_48_address0;
output   weights_buf_48_ce0;
input  [7:0] weights_buf_48_q0;
output  [6:0] weights_buf_49_address0;
output   weights_buf_49_ce0;
input  [7:0] weights_buf_49_q0;
output  [6:0] weights_buf_50_address0;
output   weights_buf_50_ce0;
input  [7:0] weights_buf_50_q0;
output  [6:0] weights_buf_51_address0;
output   weights_buf_51_ce0;
input  [7:0] weights_buf_51_q0;
output  [6:0] weights_buf_52_address0;
output   weights_buf_52_ce0;
input  [7:0] weights_buf_52_q0;
output  [6:0] weights_buf_53_address0;
output   weights_buf_53_ce0;
input  [7:0] weights_buf_53_q0;
output  [6:0] weights_buf_54_address0;
output   weights_buf_54_ce0;
input  [7:0] weights_buf_54_q0;
output  [6:0] weights_buf_55_address0;
output   weights_buf_55_ce0;
input  [7:0] weights_buf_55_q0;
output  [6:0] weights_buf_56_address0;
output   weights_buf_56_ce0;
input  [7:0] weights_buf_56_q0;
output  [6:0] weights_buf_57_address0;
output   weights_buf_57_ce0;
input  [7:0] weights_buf_57_q0;
output  [6:0] weights_buf_58_address0;
output   weights_buf_58_ce0;
input  [7:0] weights_buf_58_q0;
output  [6:0] weights_buf_59_address0;
output   weights_buf_59_ce0;
input  [7:0] weights_buf_59_q0;
output  [6:0] weights_buf_60_address0;
output   weights_buf_60_ce0;
input  [7:0] weights_buf_60_q0;
output  [6:0] weights_buf_61_address0;
output   weights_buf_61_ce0;
input  [7:0] weights_buf_61_q0;
output  [6:0] weights_buf_62_address0;
output   weights_buf_62_ce0;
input  [7:0] weights_buf_62_q0;
output  [6:0] weights_buf_63_address0;
output   weights_buf_63_ce0;
input  [7:0] weights_buf_63_q0;
input  [38:0] out_index;
input  [31:0] sext_ln58;
output  [3:0] lookup_values_address0;
output   lookup_values_ce0;
input  [7:0] lookup_values_q0;
input  [7:0] sext_ln100_3;
output  [7:0] DQ_bram;
output   DQ_bram_ap_vld;

reg ap_idle;
reg DQ_bram_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_714_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [13:0] sext_ln100_3_cast_fu_662_p1;
reg  signed [13:0] sext_ln100_3_cast_reg_975;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] trunc_ln6_reg_984;
wire   [0:0] icmp_ln100_fu_766_p2;
reg   [0:0] icmp_ln100_reg_1149;
wire   [0:0] or_ln87_fu_772_p2;
reg   [0:0] or_ln87_reg_1154;
reg   [0:0] or_ln87_reg_1154_pp0_iter1_reg;
wire   [63:0] indvars_iv35_udiv_cast_cast_fu_670_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln100_fu_943_p1;
reg   [6:0] i_fu_198;
wire   [6:0] add_ln87_fu_778_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
reg    weights_buf_32_ce0_local;
reg    weights_buf_33_ce0_local;
reg    weights_buf_34_ce0_local;
reg    weights_buf_35_ce0_local;
reg    weights_buf_36_ce0_local;
reg    weights_buf_37_ce0_local;
reg    weights_buf_38_ce0_local;
reg    weights_buf_39_ce0_local;
reg    weights_buf_40_ce0_local;
reg    weights_buf_41_ce0_local;
reg    weights_buf_42_ce0_local;
reg    weights_buf_43_ce0_local;
reg    weights_buf_44_ce0_local;
reg    weights_buf_45_ce0_local;
reg    weights_buf_46_ce0_local;
reg    weights_buf_47_ce0_local;
reg    weights_buf_48_ce0_local;
reg    weights_buf_49_ce0_local;
reg    weights_buf_50_ce0_local;
reg    weights_buf_51_ce0_local;
reg    weights_buf_52_ce0_local;
reg    weights_buf_53_ce0_local;
reg    weights_buf_54_ce0_local;
reg    weights_buf_55_ce0_local;
reg    weights_buf_56_ce0_local;
reg    weights_buf_57_ce0_local;
reg    weights_buf_58_ce0_local;
reg    weights_buf_59_ce0_local;
reg    weights_buf_60_ce0_local;
reg    weights_buf_61_ce0_local;
reg    weights_buf_62_ce0_local;
reg    weights_buf_63_ce0_local;
reg    lookup_values_ce0_local;
wire   [5:0] trunc_ln98_fu_732_p1;
wire   [6:0] zext_ln98_cast_fu_736_p3;
wire   [38:0] zext_ln98_fu_744_p1;
wire   [38:0] add_ln98_fu_748_p2;
wire  signed [38:0] sext_ln58_cast_fu_666_p1;
wire   [38:0] add_ln100_fu_760_p2;
wire   [0:0] icmp_ln98_fu_754_p2;
wire   [7:0] packed_fu_789_p65;
wire   [7:0] packed_fu_789_p67;
wire   [3:0] q1_fu_928_p3;
wire   [3:0] q0_fu_924_p1;
wire   [3:0] select_ln100_fu_936_p3;
wire  signed [7:0] mul_ln100_fu_952_p1;
wire   [13:0] mul_ln100_fu_952_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] packed_fu_789_p1;
wire   [4:0] packed_fu_789_p3;
wire   [4:0] packed_fu_789_p5;
wire   [4:0] packed_fu_789_p7;
wire   [4:0] packed_fu_789_p9;
wire   [4:0] packed_fu_789_p11;
wire   [4:0] packed_fu_789_p13;
wire   [4:0] packed_fu_789_p15;
wire   [4:0] packed_fu_789_p17;
wire   [4:0] packed_fu_789_p19;
wire   [4:0] packed_fu_789_p21;
wire   [4:0] packed_fu_789_p23;
wire   [4:0] packed_fu_789_p25;
wire   [4:0] packed_fu_789_p27;
wire   [4:0] packed_fu_789_p29;
wire   [4:0] packed_fu_789_p31;
wire  signed [4:0] packed_fu_789_p33;
wire  signed [4:0] packed_fu_789_p35;
wire  signed [4:0] packed_fu_789_p37;
wire  signed [4:0] packed_fu_789_p39;
wire  signed [4:0] packed_fu_789_p41;
wire  signed [4:0] packed_fu_789_p43;
wire  signed [4:0] packed_fu_789_p45;
wire  signed [4:0] packed_fu_789_p47;
wire  signed [4:0] packed_fu_789_p49;
wire  signed [4:0] packed_fu_789_p51;
wire  signed [4:0] packed_fu_789_p53;
wire  signed [4:0] packed_fu_789_p55;
wire  signed [4:0] packed_fu_789_p57;
wire  signed [4:0] packed_fu_789_p59;
wire  signed [4:0] packed_fu_789_p61;
wire  signed [4:0] packed_fu_789_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_198 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) dequantize_nf4_q2_6_sparsemux_65_5_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 8 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 8 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 8 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 8 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 8 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 8 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 8 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 8 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 8 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 8 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 8 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 8 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 8 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 8 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 8 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 8 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 8 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 8 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 8 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 8 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 8 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 8 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 8 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 8 ))
sparsemux_65_5_8_1_1_U622(
    .din0(weights_buf_32_q0),
    .din1(weights_buf_33_q0),
    .din2(weights_buf_34_q0),
    .din3(weights_buf_35_q0),
    .din4(weights_buf_36_q0),
    .din5(weights_buf_37_q0),
    .din6(weights_buf_38_q0),
    .din7(weights_buf_39_q0),
    .din8(weights_buf_40_q0),
    .din9(weights_buf_41_q0),
    .din10(weights_buf_42_q0),
    .din11(weights_buf_43_q0),
    .din12(weights_buf_44_q0),
    .din13(weights_buf_45_q0),
    .din14(weights_buf_46_q0),
    .din15(weights_buf_47_q0),
    .din16(weights_buf_48_q0),
    .din17(weights_buf_49_q0),
    .din18(weights_buf_50_q0),
    .din19(weights_buf_51_q0),
    .din20(weights_buf_52_q0),
    .din21(weights_buf_53_q0),
    .din22(weights_buf_54_q0),
    .din23(weights_buf_55_q0),
    .din24(weights_buf_56_q0),
    .din25(weights_buf_57_q0),
    .din26(weights_buf_58_q0),
    .din27(weights_buf_59_q0),
    .din28(weights_buf_60_q0),
    .din29(weights_buf_61_q0),
    .din30(weights_buf_62_q0),
    .din31(weights_buf_63_q0),
    .def(packed_fu_789_p65),
    .sel(trunc_ln6_reg_984),
    .dout(packed_fu_789_p67)
);

dequantize_nf4_q2_6_mul_8s_8s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 14 ))
mul_8s_8s_14_1_1_U623(
    .din0(lookup_values_q0),
    .din1(mul_ln100_fu_952_p1),
    .dout(mul_ln100_fu_952_p2)
);

dequantize_nf4_q2_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_714_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_198 <= add_ln87_fu_778_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_198 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln100_reg_1149 <= icmp_ln100_fu_766_p2;
        or_ln87_reg_1154 <= or_ln87_fu_772_p2;
        or_ln87_reg_1154_pp0_iter1_reg <= or_ln87_reg_1154;
        sext_ln100_3_cast_reg_975 <= sext_ln100_3_cast_fu_662_p1;
        trunc_ln6_reg_984 <= {{ap_sig_allocacmp_i_1[5:1]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln87_reg_1154_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        DQ_bram_ap_vld = 1'b1;
    end else begin
        DQ_bram_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_714_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lookup_values_ce0_local = 1'b1;
    end else begin
        lookup_values_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_32_ce0_local = 1'b1;
    end else begin
        weights_buf_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_33_ce0_local = 1'b1;
    end else begin
        weights_buf_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_34_ce0_local = 1'b1;
    end else begin
        weights_buf_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_35_ce0_local = 1'b1;
    end else begin
        weights_buf_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_36_ce0_local = 1'b1;
    end else begin
        weights_buf_36_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_37_ce0_local = 1'b1;
    end else begin
        weights_buf_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_38_ce0_local = 1'b1;
    end else begin
        weights_buf_38_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_39_ce0_local = 1'b1;
    end else begin
        weights_buf_39_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_40_ce0_local = 1'b1;
    end else begin
        weights_buf_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_41_ce0_local = 1'b1;
    end else begin
        weights_buf_41_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_42_ce0_local = 1'b1;
    end else begin
        weights_buf_42_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_43_ce0_local = 1'b1;
    end else begin
        weights_buf_43_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_44_ce0_local = 1'b1;
    end else begin
        weights_buf_44_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_45_ce0_local = 1'b1;
    end else begin
        weights_buf_45_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_46_ce0_local = 1'b1;
    end else begin
        weights_buf_46_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_47_ce0_local = 1'b1;
    end else begin
        weights_buf_47_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_48_ce0_local = 1'b1;
    end else begin
        weights_buf_48_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_49_ce0_local = 1'b1;
    end else begin
        weights_buf_49_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_50_ce0_local = 1'b1;
    end else begin
        weights_buf_50_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_51_ce0_local = 1'b1;
    end else begin
        weights_buf_51_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_52_ce0_local = 1'b1;
    end else begin
        weights_buf_52_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_53_ce0_local = 1'b1;
    end else begin
        weights_buf_53_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_54_ce0_local = 1'b1;
    end else begin
        weights_buf_54_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_55_ce0_local = 1'b1;
    end else begin
        weights_buf_55_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_56_ce0_local = 1'b1;
    end else begin
        weights_buf_56_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_57_ce0_local = 1'b1;
    end else begin
        weights_buf_57_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_58_ce0_local = 1'b1;
    end else begin
        weights_buf_58_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_59_ce0_local = 1'b1;
    end else begin
        weights_buf_59_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_60_ce0_local = 1'b1;
    end else begin
        weights_buf_60_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_61_ce0_local = 1'b1;
    end else begin
        weights_buf_61_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_62_ce0_local = 1'b1;
    end else begin
        weights_buf_62_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_buf_63_ce0_local = 1'b1;
    end else begin
        weights_buf_63_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DQ_bram = {{mul_ln100_fu_952_p2[13:6]}};

assign add_ln100_fu_760_p2 = (add_ln98_fu_748_p2 + 39'd1);

assign add_ln87_fu_778_p2 = (ap_sig_allocacmp_i_1 + 7'd2);

assign add_ln98_fu_748_p2 = (zext_ln98_fu_744_p1 + out_index);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln100_fu_766_p2 = (($signed(add_ln100_fu_760_p2) < $signed(sext_ln58_cast_fu_666_p1)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_754_p2 = (($signed(add_ln98_fu_748_p2) < $signed(sext_ln58_cast_fu_666_p1)) ? 1'b1 : 1'b0);

assign indvars_iv35_udiv_cast_cast_fu_670_p1 = indvars_iv35_udiv_cast;

assign lookup_values_address0 = zext_ln100_fu_943_p1;

assign lookup_values_ce0 = lookup_values_ce0_local;

assign mul_ln100_fu_952_p1 = sext_ln100_3_cast_reg_975;

assign or_ln87_fu_772_p2 = (icmp_ln98_fu_754_p2 | icmp_ln100_fu_766_p2);

assign packed_fu_789_p65 = 'bx;

assign q0_fu_924_p1 = packed_fu_789_p67[3:0];

assign q1_fu_928_p3 = {{packed_fu_789_p67[7:4]}};

assign select_ln100_fu_936_p3 = ((icmp_ln100_reg_1149[0:0] == 1'b1) ? q1_fu_928_p3 : q0_fu_924_p1);

assign sext_ln100_3_cast_fu_662_p1 = $signed(sext_ln100_3);

assign sext_ln58_cast_fu_666_p1 = $signed(sext_ln58);

assign tmp_fu_714_p3 = ap_sig_allocacmp_i_1[32'd6];

assign trunc_ln98_fu_732_p1 = ap_sig_allocacmp_i_1[5:0];

assign weights_buf_32_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_32_ce0 = weights_buf_32_ce0_local;

assign weights_buf_33_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_33_ce0 = weights_buf_33_ce0_local;

assign weights_buf_34_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_34_ce0 = weights_buf_34_ce0_local;

assign weights_buf_35_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_35_ce0 = weights_buf_35_ce0_local;

assign weights_buf_36_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_36_ce0 = weights_buf_36_ce0_local;

assign weights_buf_37_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_37_ce0 = weights_buf_37_ce0_local;

assign weights_buf_38_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_38_ce0 = weights_buf_38_ce0_local;

assign weights_buf_39_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_39_ce0 = weights_buf_39_ce0_local;

assign weights_buf_40_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_40_ce0 = weights_buf_40_ce0_local;

assign weights_buf_41_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_41_ce0 = weights_buf_41_ce0_local;

assign weights_buf_42_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_42_ce0 = weights_buf_42_ce0_local;

assign weights_buf_43_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_43_ce0 = weights_buf_43_ce0_local;

assign weights_buf_44_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_44_ce0 = weights_buf_44_ce0_local;

assign weights_buf_45_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_45_ce0 = weights_buf_45_ce0_local;

assign weights_buf_46_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_46_ce0 = weights_buf_46_ce0_local;

assign weights_buf_47_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_47_ce0 = weights_buf_47_ce0_local;

assign weights_buf_48_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_48_ce0 = weights_buf_48_ce0_local;

assign weights_buf_49_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_49_ce0 = weights_buf_49_ce0_local;

assign weights_buf_50_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_50_ce0 = weights_buf_50_ce0_local;

assign weights_buf_51_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_51_ce0 = weights_buf_51_ce0_local;

assign weights_buf_52_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_52_ce0 = weights_buf_52_ce0_local;

assign weights_buf_53_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_53_ce0 = weights_buf_53_ce0_local;

assign weights_buf_54_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_54_ce0 = weights_buf_54_ce0_local;

assign weights_buf_55_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_55_ce0 = weights_buf_55_ce0_local;

assign weights_buf_56_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_56_ce0 = weights_buf_56_ce0_local;

assign weights_buf_57_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_57_ce0 = weights_buf_57_ce0_local;

assign weights_buf_58_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_58_ce0 = weights_buf_58_ce0_local;

assign weights_buf_59_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_59_ce0 = weights_buf_59_ce0_local;

assign weights_buf_60_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_60_ce0 = weights_buf_60_ce0_local;

assign weights_buf_61_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_61_ce0 = weights_buf_61_ce0_local;

assign weights_buf_62_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_62_ce0 = weights_buf_62_ce0_local;

assign weights_buf_63_address0 = indvars_iv35_udiv_cast_cast_fu_670_p1;

assign weights_buf_63_ce0 = weights_buf_63_ce0_local;

assign zext_ln100_fu_943_p1 = select_ln100_fu_936_p3;

assign zext_ln98_cast_fu_736_p3 = {{1'd1}, {trunc_ln98_fu_732_p1}};

assign zext_ln98_fu_744_p1 = zext_ln98_cast_fu_736_p3;

endmodule //dequantize_nf4_q2_6_dequantize_nf4_q2_6_Pipeline_VITIS_LOOP_87_51
