// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dequantize_nf4_q2_6_dequantize_nf4_q2_6_Pipeline_VITIS_LOOP_74_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_5,
        input_weights_load,
        weights_buf_63_address0,
        weights_buf_63_ce0,
        weights_buf_63_we0,
        weights_buf_63_d0,
        weights_buf_62_address0,
        weights_buf_62_ce0,
        weights_buf_62_we0,
        weights_buf_62_d0,
        weights_buf_61_address0,
        weights_buf_61_ce0,
        weights_buf_61_we0,
        weights_buf_61_d0,
        weights_buf_60_address0,
        weights_buf_60_ce0,
        weights_buf_60_we0,
        weights_buf_60_d0,
        weights_buf_59_address0,
        weights_buf_59_ce0,
        weights_buf_59_we0,
        weights_buf_59_d0,
        weights_buf_58_address0,
        weights_buf_58_ce0,
        weights_buf_58_we0,
        weights_buf_58_d0,
        weights_buf_57_address0,
        weights_buf_57_ce0,
        weights_buf_57_we0,
        weights_buf_57_d0,
        weights_buf_56_address0,
        weights_buf_56_ce0,
        weights_buf_56_we0,
        weights_buf_56_d0,
        weights_buf_55_address0,
        weights_buf_55_ce0,
        weights_buf_55_we0,
        weights_buf_55_d0,
        weights_buf_54_address0,
        weights_buf_54_ce0,
        weights_buf_54_we0,
        weights_buf_54_d0,
        weights_buf_53_address0,
        weights_buf_53_ce0,
        weights_buf_53_we0,
        weights_buf_53_d0,
        weights_buf_52_address0,
        weights_buf_52_ce0,
        weights_buf_52_we0,
        weights_buf_52_d0,
        weights_buf_51_address0,
        weights_buf_51_ce0,
        weights_buf_51_we0,
        weights_buf_51_d0,
        weights_buf_50_address0,
        weights_buf_50_ce0,
        weights_buf_50_we0,
        weights_buf_50_d0,
        weights_buf_49_address0,
        weights_buf_49_ce0,
        weights_buf_49_we0,
        weights_buf_49_d0,
        weights_buf_48_address0,
        weights_buf_48_ce0,
        weights_buf_48_we0,
        weights_buf_48_d0,
        weights_buf_47_address0,
        weights_buf_47_ce0,
        weights_buf_47_we0,
        weights_buf_47_d0,
        weights_buf_46_address0,
        weights_buf_46_ce0,
        weights_buf_46_we0,
        weights_buf_46_d0,
        weights_buf_45_address0,
        weights_buf_45_ce0,
        weights_buf_45_we0,
        weights_buf_45_d0,
        weights_buf_44_address0,
        weights_buf_44_ce0,
        weights_buf_44_we0,
        weights_buf_44_d0,
        weights_buf_43_address0,
        weights_buf_43_ce0,
        weights_buf_43_we0,
        weights_buf_43_d0,
        weights_buf_42_address0,
        weights_buf_42_ce0,
        weights_buf_42_we0,
        weights_buf_42_d0,
        weights_buf_41_address0,
        weights_buf_41_ce0,
        weights_buf_41_we0,
        weights_buf_41_d0,
        weights_buf_40_address0,
        weights_buf_40_ce0,
        weights_buf_40_we0,
        weights_buf_40_d0,
        weights_buf_39_address0,
        weights_buf_39_ce0,
        weights_buf_39_we0,
        weights_buf_39_d0,
        weights_buf_38_address0,
        weights_buf_38_ce0,
        weights_buf_38_we0,
        weights_buf_38_d0,
        weights_buf_37_address0,
        weights_buf_37_ce0,
        weights_buf_37_we0,
        weights_buf_37_d0,
        weights_buf_36_address0,
        weights_buf_36_ce0,
        weights_buf_36_we0,
        weights_buf_36_d0,
        weights_buf_35_address0,
        weights_buf_35_ce0,
        weights_buf_35_we0,
        weights_buf_35_d0,
        weights_buf_34_address0,
        weights_buf_34_ce0,
        weights_buf_34_we0,
        weights_buf_34_d0,
        weights_buf_33_address0,
        weights_buf_33_ce0,
        weights_buf_33_we0,
        weights_buf_33_d0,
        weights_buf_32_address0,
        weights_buf_32_ce0,
        weights_buf_32_we0,
        weights_buf_32_d0,
        weights_buf_31_address0,
        weights_buf_31_ce0,
        weights_buf_31_we0,
        weights_buf_31_d0,
        weights_buf_30_address0,
        weights_buf_30_ce0,
        weights_buf_30_we0,
        weights_buf_30_d0,
        weights_buf_29_address0,
        weights_buf_29_ce0,
        weights_buf_29_we0,
        weights_buf_29_d0,
        weights_buf_28_address0,
        weights_buf_28_ce0,
        weights_buf_28_we0,
        weights_buf_28_d0,
        weights_buf_27_address0,
        weights_buf_27_ce0,
        weights_buf_27_we0,
        weights_buf_27_d0,
        weights_buf_26_address0,
        weights_buf_26_ce0,
        weights_buf_26_we0,
        weights_buf_26_d0,
        weights_buf_25_address0,
        weights_buf_25_ce0,
        weights_buf_25_we0,
        weights_buf_25_d0,
        weights_buf_24_address0,
        weights_buf_24_ce0,
        weights_buf_24_we0,
        weights_buf_24_d0,
        weights_buf_23_address0,
        weights_buf_23_ce0,
        weights_buf_23_we0,
        weights_buf_23_d0,
        weights_buf_22_address0,
        weights_buf_22_ce0,
        weights_buf_22_we0,
        weights_buf_22_d0,
        weights_buf_21_address0,
        weights_buf_21_ce0,
        weights_buf_21_we0,
        weights_buf_21_d0,
        weights_buf_20_address0,
        weights_buf_20_ce0,
        weights_buf_20_we0,
        weights_buf_20_d0,
        weights_buf_19_address0,
        weights_buf_19_ce0,
        weights_buf_19_we0,
        weights_buf_19_d0,
        weights_buf_18_address0,
        weights_buf_18_ce0,
        weights_buf_18_we0,
        weights_buf_18_d0,
        weights_buf_17_address0,
        weights_buf_17_ce0,
        weights_buf_17_we0,
        weights_buf_17_d0,
        weights_buf_16_address0,
        weights_buf_16_ce0,
        weights_buf_16_we0,
        weights_buf_16_d0,
        weights_buf_15_address0,
        weights_buf_15_ce0,
        weights_buf_15_we0,
        weights_buf_15_d0,
        weights_buf_14_address0,
        weights_buf_14_ce0,
        weights_buf_14_we0,
        weights_buf_14_d0,
        weights_buf_13_address0,
        weights_buf_13_ce0,
        weights_buf_13_we0,
        weights_buf_13_d0,
        weights_buf_12_address0,
        weights_buf_12_ce0,
        weights_buf_12_we0,
        weights_buf_12_d0,
        weights_buf_11_address0,
        weights_buf_11_ce0,
        weights_buf_11_we0,
        weights_buf_11_d0,
        weights_buf_10_address0,
        weights_buf_10_ce0,
        weights_buf_10_we0,
        weights_buf_10_d0,
        weights_buf_9_address0,
        weights_buf_9_ce0,
        weights_buf_9_we0,
        weights_buf_9_d0,
        weights_buf_8_address0,
        weights_buf_8_ce0,
        weights_buf_8_we0,
        weights_buf_8_d0,
        weights_buf_7_address0,
        weights_buf_7_ce0,
        weights_buf_7_we0,
        weights_buf_7_d0,
        weights_buf_6_address0,
        weights_buf_6_ce0,
        weights_buf_6_we0,
        weights_buf_6_d0,
        weights_buf_5_address0,
        weights_buf_5_ce0,
        weights_buf_5_we0,
        weights_buf_5_d0,
        weights_buf_4_address0,
        weights_buf_4_ce0,
        weights_buf_4_we0,
        weights_buf_4_d0,
        weights_buf_3_address0,
        weights_buf_3_ce0,
        weights_buf_3_we0,
        weights_buf_3_d0,
        weights_buf_2_address0,
        weights_buf_2_ce0,
        weights_buf_2_we0,
        weights_buf_2_d0,
        weights_buf_1_address0,
        weights_buf_1_ce0,
        weights_buf_1_we0,
        weights_buf_1_d0,
        weights_buf_address0,
        weights_buf_ce0,
        weights_buf_we0,
        weights_buf_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [30:0] tmp_5;
input  [7:0] input_weights_load;
output  [6:0] weights_buf_63_address0;
output   weights_buf_63_ce0;
output   weights_buf_63_we0;
output  [7:0] weights_buf_63_d0;
output  [6:0] weights_buf_62_address0;
output   weights_buf_62_ce0;
output   weights_buf_62_we0;
output  [7:0] weights_buf_62_d0;
output  [6:0] weights_buf_61_address0;
output   weights_buf_61_ce0;
output   weights_buf_61_we0;
output  [7:0] weights_buf_61_d0;
output  [6:0] weights_buf_60_address0;
output   weights_buf_60_ce0;
output   weights_buf_60_we0;
output  [7:0] weights_buf_60_d0;
output  [6:0] weights_buf_59_address0;
output   weights_buf_59_ce0;
output   weights_buf_59_we0;
output  [7:0] weights_buf_59_d0;
output  [6:0] weights_buf_58_address0;
output   weights_buf_58_ce0;
output   weights_buf_58_we0;
output  [7:0] weights_buf_58_d0;
output  [6:0] weights_buf_57_address0;
output   weights_buf_57_ce0;
output   weights_buf_57_we0;
output  [7:0] weights_buf_57_d0;
output  [6:0] weights_buf_56_address0;
output   weights_buf_56_ce0;
output   weights_buf_56_we0;
output  [7:0] weights_buf_56_d0;
output  [6:0] weights_buf_55_address0;
output   weights_buf_55_ce0;
output   weights_buf_55_we0;
output  [7:0] weights_buf_55_d0;
output  [6:0] weights_buf_54_address0;
output   weights_buf_54_ce0;
output   weights_buf_54_we0;
output  [7:0] weights_buf_54_d0;
output  [6:0] weights_buf_53_address0;
output   weights_buf_53_ce0;
output   weights_buf_53_we0;
output  [7:0] weights_buf_53_d0;
output  [6:0] weights_buf_52_address0;
output   weights_buf_52_ce0;
output   weights_buf_52_we0;
output  [7:0] weights_buf_52_d0;
output  [6:0] weights_buf_51_address0;
output   weights_buf_51_ce0;
output   weights_buf_51_we0;
output  [7:0] weights_buf_51_d0;
output  [6:0] weights_buf_50_address0;
output   weights_buf_50_ce0;
output   weights_buf_50_we0;
output  [7:0] weights_buf_50_d0;
output  [6:0] weights_buf_49_address0;
output   weights_buf_49_ce0;
output   weights_buf_49_we0;
output  [7:0] weights_buf_49_d0;
output  [6:0] weights_buf_48_address0;
output   weights_buf_48_ce0;
output   weights_buf_48_we0;
output  [7:0] weights_buf_48_d0;
output  [6:0] weights_buf_47_address0;
output   weights_buf_47_ce0;
output   weights_buf_47_we0;
output  [7:0] weights_buf_47_d0;
output  [6:0] weights_buf_46_address0;
output   weights_buf_46_ce0;
output   weights_buf_46_we0;
output  [7:0] weights_buf_46_d0;
output  [6:0] weights_buf_45_address0;
output   weights_buf_45_ce0;
output   weights_buf_45_we0;
output  [7:0] weights_buf_45_d0;
output  [6:0] weights_buf_44_address0;
output   weights_buf_44_ce0;
output   weights_buf_44_we0;
output  [7:0] weights_buf_44_d0;
output  [6:0] weights_buf_43_address0;
output   weights_buf_43_ce0;
output   weights_buf_43_we0;
output  [7:0] weights_buf_43_d0;
output  [6:0] weights_buf_42_address0;
output   weights_buf_42_ce0;
output   weights_buf_42_we0;
output  [7:0] weights_buf_42_d0;
output  [6:0] weights_buf_41_address0;
output   weights_buf_41_ce0;
output   weights_buf_41_we0;
output  [7:0] weights_buf_41_d0;
output  [6:0] weights_buf_40_address0;
output   weights_buf_40_ce0;
output   weights_buf_40_we0;
output  [7:0] weights_buf_40_d0;
output  [6:0] weights_buf_39_address0;
output   weights_buf_39_ce0;
output   weights_buf_39_we0;
output  [7:0] weights_buf_39_d0;
output  [6:0] weights_buf_38_address0;
output   weights_buf_38_ce0;
output   weights_buf_38_we0;
output  [7:0] weights_buf_38_d0;
output  [6:0] weights_buf_37_address0;
output   weights_buf_37_ce0;
output   weights_buf_37_we0;
output  [7:0] weights_buf_37_d0;
output  [6:0] weights_buf_36_address0;
output   weights_buf_36_ce0;
output   weights_buf_36_we0;
output  [7:0] weights_buf_36_d0;
output  [6:0] weights_buf_35_address0;
output   weights_buf_35_ce0;
output   weights_buf_35_we0;
output  [7:0] weights_buf_35_d0;
output  [6:0] weights_buf_34_address0;
output   weights_buf_34_ce0;
output   weights_buf_34_we0;
output  [7:0] weights_buf_34_d0;
output  [6:0] weights_buf_33_address0;
output   weights_buf_33_ce0;
output   weights_buf_33_we0;
output  [7:0] weights_buf_33_d0;
output  [6:0] weights_buf_32_address0;
output   weights_buf_32_ce0;
output   weights_buf_32_we0;
output  [7:0] weights_buf_32_d0;
output  [6:0] weights_buf_31_address0;
output   weights_buf_31_ce0;
output   weights_buf_31_we0;
output  [7:0] weights_buf_31_d0;
output  [6:0] weights_buf_30_address0;
output   weights_buf_30_ce0;
output   weights_buf_30_we0;
output  [7:0] weights_buf_30_d0;
output  [6:0] weights_buf_29_address0;
output   weights_buf_29_ce0;
output   weights_buf_29_we0;
output  [7:0] weights_buf_29_d0;
output  [6:0] weights_buf_28_address0;
output   weights_buf_28_ce0;
output   weights_buf_28_we0;
output  [7:0] weights_buf_28_d0;
output  [6:0] weights_buf_27_address0;
output   weights_buf_27_ce0;
output   weights_buf_27_we0;
output  [7:0] weights_buf_27_d0;
output  [6:0] weights_buf_26_address0;
output   weights_buf_26_ce0;
output   weights_buf_26_we0;
output  [7:0] weights_buf_26_d0;
output  [6:0] weights_buf_25_address0;
output   weights_buf_25_ce0;
output   weights_buf_25_we0;
output  [7:0] weights_buf_25_d0;
output  [6:0] weights_buf_24_address0;
output   weights_buf_24_ce0;
output   weights_buf_24_we0;
output  [7:0] weights_buf_24_d0;
output  [6:0] weights_buf_23_address0;
output   weights_buf_23_ce0;
output   weights_buf_23_we0;
output  [7:0] weights_buf_23_d0;
output  [6:0] weights_buf_22_address0;
output   weights_buf_22_ce0;
output   weights_buf_22_we0;
output  [7:0] weights_buf_22_d0;
output  [6:0] weights_buf_21_address0;
output   weights_buf_21_ce0;
output   weights_buf_21_we0;
output  [7:0] weights_buf_21_d0;
output  [6:0] weights_buf_20_address0;
output   weights_buf_20_ce0;
output   weights_buf_20_we0;
output  [7:0] weights_buf_20_d0;
output  [6:0] weights_buf_19_address0;
output   weights_buf_19_ce0;
output   weights_buf_19_we0;
output  [7:0] weights_buf_19_d0;
output  [6:0] weights_buf_18_address0;
output   weights_buf_18_ce0;
output   weights_buf_18_we0;
output  [7:0] weights_buf_18_d0;
output  [6:0] weights_buf_17_address0;
output   weights_buf_17_ce0;
output   weights_buf_17_we0;
output  [7:0] weights_buf_17_d0;
output  [6:0] weights_buf_16_address0;
output   weights_buf_16_ce0;
output   weights_buf_16_we0;
output  [7:0] weights_buf_16_d0;
output  [6:0] weights_buf_15_address0;
output   weights_buf_15_ce0;
output   weights_buf_15_we0;
output  [7:0] weights_buf_15_d0;
output  [6:0] weights_buf_14_address0;
output   weights_buf_14_ce0;
output   weights_buf_14_we0;
output  [7:0] weights_buf_14_d0;
output  [6:0] weights_buf_13_address0;
output   weights_buf_13_ce0;
output   weights_buf_13_we0;
output  [7:0] weights_buf_13_d0;
output  [6:0] weights_buf_12_address0;
output   weights_buf_12_ce0;
output   weights_buf_12_we0;
output  [7:0] weights_buf_12_d0;
output  [6:0] weights_buf_11_address0;
output   weights_buf_11_ce0;
output   weights_buf_11_we0;
output  [7:0] weights_buf_11_d0;
output  [6:0] weights_buf_10_address0;
output   weights_buf_10_ce0;
output   weights_buf_10_we0;
output  [7:0] weights_buf_10_d0;
output  [6:0] weights_buf_9_address0;
output   weights_buf_9_ce0;
output   weights_buf_9_we0;
output  [7:0] weights_buf_9_d0;
output  [6:0] weights_buf_8_address0;
output   weights_buf_8_ce0;
output   weights_buf_8_we0;
output  [7:0] weights_buf_8_d0;
output  [6:0] weights_buf_7_address0;
output   weights_buf_7_ce0;
output   weights_buf_7_we0;
output  [7:0] weights_buf_7_d0;
output  [6:0] weights_buf_6_address0;
output   weights_buf_6_ce0;
output   weights_buf_6_we0;
output  [7:0] weights_buf_6_d0;
output  [6:0] weights_buf_5_address0;
output   weights_buf_5_ce0;
output   weights_buf_5_we0;
output  [7:0] weights_buf_5_d0;
output  [6:0] weights_buf_4_address0;
output   weights_buf_4_ce0;
output   weights_buf_4_we0;
output  [7:0] weights_buf_4_d0;
output  [6:0] weights_buf_3_address0;
output   weights_buf_3_ce0;
output   weights_buf_3_we0;
output  [7:0] weights_buf_3_d0;
output  [6:0] weights_buf_2_address0;
output   weights_buf_2_ce0;
output   weights_buf_2_we0;
output  [7:0] weights_buf_2_d0;
output  [6:0] weights_buf_1_address0;
output   weights_buf_1_ce0;
output   weights_buf_1_we0;
output  [7:0] weights_buf_1_d0;
output  [6:0] weights_buf_address0;
output   weights_buf_ce0;
output   weights_buf_we0;
output  [7:0] weights_buf_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln74_fu_1216_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln74_1_fu_1242_p1;
reg   [29:0] i_1_fu_292;
wire   [29:0] add_ln74_fu_1222_p2;
wire    ap_loop_init;
reg   [29:0] ap_sig_allocacmp_i;
reg    weights_buf_62_we0_local;
wire   [5:0] trunc_ln74_fu_1228_p1;
reg    weights_buf_62_ce0_local;
reg    weights_buf_61_we0_local;
reg    weights_buf_61_ce0_local;
reg    weights_buf_60_we0_local;
reg    weights_buf_60_ce0_local;
reg    weights_buf_59_we0_local;
reg    weights_buf_59_ce0_local;
reg    weights_buf_58_we0_local;
reg    weights_buf_58_ce0_local;
reg    weights_buf_57_we0_local;
reg    weights_buf_57_ce0_local;
reg    weights_buf_56_we0_local;
reg    weights_buf_56_ce0_local;
reg    weights_buf_55_we0_local;
reg    weights_buf_55_ce0_local;
reg    weights_buf_54_we0_local;
reg    weights_buf_54_ce0_local;
reg    weights_buf_53_we0_local;
reg    weights_buf_53_ce0_local;
reg    weights_buf_52_we0_local;
reg    weights_buf_52_ce0_local;
reg    weights_buf_51_we0_local;
reg    weights_buf_51_ce0_local;
reg    weights_buf_50_we0_local;
reg    weights_buf_50_ce0_local;
reg    weights_buf_49_we0_local;
reg    weights_buf_49_ce0_local;
reg    weights_buf_48_we0_local;
reg    weights_buf_48_ce0_local;
reg    weights_buf_47_we0_local;
reg    weights_buf_47_ce0_local;
reg    weights_buf_46_we0_local;
reg    weights_buf_46_ce0_local;
reg    weights_buf_45_we0_local;
reg    weights_buf_45_ce0_local;
reg    weights_buf_44_we0_local;
reg    weights_buf_44_ce0_local;
reg    weights_buf_43_we0_local;
reg    weights_buf_43_ce0_local;
reg    weights_buf_42_we0_local;
reg    weights_buf_42_ce0_local;
reg    weights_buf_41_we0_local;
reg    weights_buf_41_ce0_local;
reg    weights_buf_40_we0_local;
reg    weights_buf_40_ce0_local;
reg    weights_buf_39_we0_local;
reg    weights_buf_39_ce0_local;
reg    weights_buf_38_we0_local;
reg    weights_buf_38_ce0_local;
reg    weights_buf_37_we0_local;
reg    weights_buf_37_ce0_local;
reg    weights_buf_36_we0_local;
reg    weights_buf_36_ce0_local;
reg    weights_buf_35_we0_local;
reg    weights_buf_35_ce0_local;
reg    weights_buf_34_we0_local;
reg    weights_buf_34_ce0_local;
reg    weights_buf_33_we0_local;
reg    weights_buf_33_ce0_local;
reg    weights_buf_32_we0_local;
reg    weights_buf_32_ce0_local;
reg    weights_buf_31_we0_local;
reg    weights_buf_31_ce0_local;
reg    weights_buf_30_we0_local;
reg    weights_buf_30_ce0_local;
reg    weights_buf_29_we0_local;
reg    weights_buf_29_ce0_local;
reg    weights_buf_28_we0_local;
reg    weights_buf_28_ce0_local;
reg    weights_buf_27_we0_local;
reg    weights_buf_27_ce0_local;
reg    weights_buf_26_we0_local;
reg    weights_buf_26_ce0_local;
reg    weights_buf_25_we0_local;
reg    weights_buf_25_ce0_local;
reg    weights_buf_24_we0_local;
reg    weights_buf_24_ce0_local;
reg    weights_buf_23_we0_local;
reg    weights_buf_23_ce0_local;
reg    weights_buf_22_we0_local;
reg    weights_buf_22_ce0_local;
reg    weights_buf_21_we0_local;
reg    weights_buf_21_ce0_local;
reg    weights_buf_20_we0_local;
reg    weights_buf_20_ce0_local;
reg    weights_buf_19_we0_local;
reg    weights_buf_19_ce0_local;
reg    weights_buf_18_we0_local;
reg    weights_buf_18_ce0_local;
reg    weights_buf_17_we0_local;
reg    weights_buf_17_ce0_local;
reg    weights_buf_16_we0_local;
reg    weights_buf_16_ce0_local;
reg    weights_buf_15_we0_local;
reg    weights_buf_15_ce0_local;
reg    weights_buf_14_we0_local;
reg    weights_buf_14_ce0_local;
reg    weights_buf_13_we0_local;
reg    weights_buf_13_ce0_local;
reg    weights_buf_12_we0_local;
reg    weights_buf_12_ce0_local;
reg    weights_buf_11_we0_local;
reg    weights_buf_11_ce0_local;
reg    weights_buf_10_we0_local;
reg    weights_buf_10_ce0_local;
reg    weights_buf_9_we0_local;
reg    weights_buf_9_ce0_local;
reg    weights_buf_8_we0_local;
reg    weights_buf_8_ce0_local;
reg    weights_buf_7_we0_local;
reg    weights_buf_7_ce0_local;
reg    weights_buf_6_we0_local;
reg    weights_buf_6_ce0_local;
reg    weights_buf_5_we0_local;
reg    weights_buf_5_ce0_local;
reg    weights_buf_4_we0_local;
reg    weights_buf_4_ce0_local;
reg    weights_buf_3_we0_local;
reg    weights_buf_3_ce0_local;
reg    weights_buf_2_we0_local;
reg    weights_buf_2_ce0_local;
reg    weights_buf_1_we0_local;
reg    weights_buf_1_ce0_local;
reg    weights_buf_we0_local;
reg    weights_buf_ce0_local;
reg    weights_buf_63_we0_local;
reg    weights_buf_63_ce0_local;
wire   [30:0] zext_ln74_fu_1212_p1;
wire   [6:0] lshr_ln_fu_1232_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_1_fu_292 = 30'd0;
#0 ap_done_reg = 1'b0;
end

dequantize_nf4_q2_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln74_fu_1216_p2 == 1'd1)) begin
            i_1_fu_292 <= add_ln74_fu_1222_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_292 <= 30'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln74_fu_1216_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i = 30'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_292;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_10_ce0_local = 1'b1;
    end else begin
        weights_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd10) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_10_we0_local = 1'b1;
    end else begin
        weights_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_11_ce0_local = 1'b1;
    end else begin
        weights_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd11) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_11_we0_local = 1'b1;
    end else begin
        weights_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_12_ce0_local = 1'b1;
    end else begin
        weights_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd12) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_12_we0_local = 1'b1;
    end else begin
        weights_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_13_ce0_local = 1'b1;
    end else begin
        weights_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd13) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_13_we0_local = 1'b1;
    end else begin
        weights_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_14_ce0_local = 1'b1;
    end else begin
        weights_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd14) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_14_we0_local = 1'b1;
    end else begin
        weights_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_15_ce0_local = 1'b1;
    end else begin
        weights_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd15) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_15_we0_local = 1'b1;
    end else begin
        weights_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_16_ce0_local = 1'b1;
    end else begin
        weights_buf_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd16) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_16_we0_local = 1'b1;
    end else begin
        weights_buf_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_17_ce0_local = 1'b1;
    end else begin
        weights_buf_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd17) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_17_we0_local = 1'b1;
    end else begin
        weights_buf_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_18_ce0_local = 1'b1;
    end else begin
        weights_buf_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd18) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_18_we0_local = 1'b1;
    end else begin
        weights_buf_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_19_ce0_local = 1'b1;
    end else begin
        weights_buf_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd19) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_19_we0_local = 1'b1;
    end else begin
        weights_buf_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_1_ce0_local = 1'b1;
    end else begin
        weights_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd1) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_1_we0_local = 1'b1;
    end else begin
        weights_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_20_ce0_local = 1'b1;
    end else begin
        weights_buf_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd20) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_20_we0_local = 1'b1;
    end else begin
        weights_buf_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_21_ce0_local = 1'b1;
    end else begin
        weights_buf_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd21) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_21_we0_local = 1'b1;
    end else begin
        weights_buf_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_22_ce0_local = 1'b1;
    end else begin
        weights_buf_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd22) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_22_we0_local = 1'b1;
    end else begin
        weights_buf_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_23_ce0_local = 1'b1;
    end else begin
        weights_buf_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd23) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_23_we0_local = 1'b1;
    end else begin
        weights_buf_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_24_ce0_local = 1'b1;
    end else begin
        weights_buf_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd24) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_24_we0_local = 1'b1;
    end else begin
        weights_buf_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_25_ce0_local = 1'b1;
    end else begin
        weights_buf_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd25) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_25_we0_local = 1'b1;
    end else begin
        weights_buf_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_26_ce0_local = 1'b1;
    end else begin
        weights_buf_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd26) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_26_we0_local = 1'b1;
    end else begin
        weights_buf_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_27_ce0_local = 1'b1;
    end else begin
        weights_buf_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd27) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_27_we0_local = 1'b1;
    end else begin
        weights_buf_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_28_ce0_local = 1'b1;
    end else begin
        weights_buf_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd28) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_28_we0_local = 1'b1;
    end else begin
        weights_buf_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_29_ce0_local = 1'b1;
    end else begin
        weights_buf_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd29) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_29_we0_local = 1'b1;
    end else begin
        weights_buf_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_2_ce0_local = 1'b1;
    end else begin
        weights_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd2) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_2_we0_local = 1'b1;
    end else begin
        weights_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_30_ce0_local = 1'b1;
    end else begin
        weights_buf_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd30) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_30_we0_local = 1'b1;
    end else begin
        weights_buf_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_31_ce0_local = 1'b1;
    end else begin
        weights_buf_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd31) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_31_we0_local = 1'b1;
    end else begin
        weights_buf_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_32_ce0_local = 1'b1;
    end else begin
        weights_buf_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd32) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_32_we0_local = 1'b1;
    end else begin
        weights_buf_32_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_33_ce0_local = 1'b1;
    end else begin
        weights_buf_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd33) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_33_we0_local = 1'b1;
    end else begin
        weights_buf_33_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_34_ce0_local = 1'b1;
    end else begin
        weights_buf_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd34) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_34_we0_local = 1'b1;
    end else begin
        weights_buf_34_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_35_ce0_local = 1'b1;
    end else begin
        weights_buf_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd35) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_35_we0_local = 1'b1;
    end else begin
        weights_buf_35_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_36_ce0_local = 1'b1;
    end else begin
        weights_buf_36_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd36) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_36_we0_local = 1'b1;
    end else begin
        weights_buf_36_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_37_ce0_local = 1'b1;
    end else begin
        weights_buf_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd37) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_37_we0_local = 1'b1;
    end else begin
        weights_buf_37_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_38_ce0_local = 1'b1;
    end else begin
        weights_buf_38_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd38) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_38_we0_local = 1'b1;
    end else begin
        weights_buf_38_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_39_ce0_local = 1'b1;
    end else begin
        weights_buf_39_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd39) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_39_we0_local = 1'b1;
    end else begin
        weights_buf_39_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_3_ce0_local = 1'b1;
    end else begin
        weights_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd3) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_3_we0_local = 1'b1;
    end else begin
        weights_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_40_ce0_local = 1'b1;
    end else begin
        weights_buf_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd40) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_40_we0_local = 1'b1;
    end else begin
        weights_buf_40_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_41_ce0_local = 1'b1;
    end else begin
        weights_buf_41_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd41) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_41_we0_local = 1'b1;
    end else begin
        weights_buf_41_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_42_ce0_local = 1'b1;
    end else begin
        weights_buf_42_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd42) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_42_we0_local = 1'b1;
    end else begin
        weights_buf_42_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_43_ce0_local = 1'b1;
    end else begin
        weights_buf_43_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd43) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_43_we0_local = 1'b1;
    end else begin
        weights_buf_43_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_44_ce0_local = 1'b1;
    end else begin
        weights_buf_44_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd44) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_44_we0_local = 1'b1;
    end else begin
        weights_buf_44_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_45_ce0_local = 1'b1;
    end else begin
        weights_buf_45_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd45) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_45_we0_local = 1'b1;
    end else begin
        weights_buf_45_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_46_ce0_local = 1'b1;
    end else begin
        weights_buf_46_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd46) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_46_we0_local = 1'b1;
    end else begin
        weights_buf_46_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_47_ce0_local = 1'b1;
    end else begin
        weights_buf_47_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd47) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_47_we0_local = 1'b1;
    end else begin
        weights_buf_47_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_48_ce0_local = 1'b1;
    end else begin
        weights_buf_48_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd48) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_48_we0_local = 1'b1;
    end else begin
        weights_buf_48_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_49_ce0_local = 1'b1;
    end else begin
        weights_buf_49_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd49) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_49_we0_local = 1'b1;
    end else begin
        weights_buf_49_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_4_ce0_local = 1'b1;
    end else begin
        weights_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd4) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_4_we0_local = 1'b1;
    end else begin
        weights_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_50_ce0_local = 1'b1;
    end else begin
        weights_buf_50_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd50) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_50_we0_local = 1'b1;
    end else begin
        weights_buf_50_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_51_ce0_local = 1'b1;
    end else begin
        weights_buf_51_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd51) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_51_we0_local = 1'b1;
    end else begin
        weights_buf_51_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_52_ce0_local = 1'b1;
    end else begin
        weights_buf_52_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd52) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_52_we0_local = 1'b1;
    end else begin
        weights_buf_52_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_53_ce0_local = 1'b1;
    end else begin
        weights_buf_53_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd53) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_53_we0_local = 1'b1;
    end else begin
        weights_buf_53_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_54_ce0_local = 1'b1;
    end else begin
        weights_buf_54_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd54) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_54_we0_local = 1'b1;
    end else begin
        weights_buf_54_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_55_ce0_local = 1'b1;
    end else begin
        weights_buf_55_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd55) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_55_we0_local = 1'b1;
    end else begin
        weights_buf_55_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_56_ce0_local = 1'b1;
    end else begin
        weights_buf_56_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd56) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_56_we0_local = 1'b1;
    end else begin
        weights_buf_56_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_57_ce0_local = 1'b1;
    end else begin
        weights_buf_57_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd57) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_57_we0_local = 1'b1;
    end else begin
        weights_buf_57_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_58_ce0_local = 1'b1;
    end else begin
        weights_buf_58_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd58) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_58_we0_local = 1'b1;
    end else begin
        weights_buf_58_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_59_ce0_local = 1'b1;
    end else begin
        weights_buf_59_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd59) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_59_we0_local = 1'b1;
    end else begin
        weights_buf_59_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_5_ce0_local = 1'b1;
    end else begin
        weights_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd5) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_5_we0_local = 1'b1;
    end else begin
        weights_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_60_ce0_local = 1'b1;
    end else begin
        weights_buf_60_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd60) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_60_we0_local = 1'b1;
    end else begin
        weights_buf_60_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_61_ce0_local = 1'b1;
    end else begin
        weights_buf_61_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd61) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_61_we0_local = 1'b1;
    end else begin
        weights_buf_61_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_62_ce0_local = 1'b1;
    end else begin
        weights_buf_62_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd62) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_62_we0_local = 1'b1;
    end else begin
        weights_buf_62_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_63_ce0_local = 1'b1;
    end else begin
        weights_buf_63_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd63) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_63_we0_local = 1'b1;
    end else begin
        weights_buf_63_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_6_ce0_local = 1'b1;
    end else begin
        weights_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd6) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_6_we0_local = 1'b1;
    end else begin
        weights_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_7_ce0_local = 1'b1;
    end else begin
        weights_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd7) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_7_we0_local = 1'b1;
    end else begin
        weights_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_8_ce0_local = 1'b1;
    end else begin
        weights_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd8) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_8_we0_local = 1'b1;
    end else begin
        weights_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_9_ce0_local = 1'b1;
    end else begin
        weights_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd9) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_9_we0_local = 1'b1;
    end else begin
        weights_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_ce0_local = 1'b1;
    end else begin
        weights_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln74_fu_1228_p1 == 6'd0) & (icmp_ln74_fu_1216_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        weights_buf_we0_local = 1'b1;
    end else begin
        weights_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_fu_1222_p2 = (ap_sig_allocacmp_i + 30'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln74_fu_1216_p2 = (($signed(zext_ln74_fu_1212_p1) < $signed(tmp_5)) ? 1'b1 : 1'b0);

assign lshr_ln_fu_1232_p4 = {{ap_sig_allocacmp_i[12:6]}};

assign trunc_ln74_fu_1228_p1 = ap_sig_allocacmp_i[5:0];

assign weights_buf_10_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_10_ce0 = weights_buf_10_ce0_local;

assign weights_buf_10_d0 = input_weights_load;

assign weights_buf_10_we0 = weights_buf_10_we0_local;

assign weights_buf_11_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_11_ce0 = weights_buf_11_ce0_local;

assign weights_buf_11_d0 = input_weights_load;

assign weights_buf_11_we0 = weights_buf_11_we0_local;

assign weights_buf_12_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_12_ce0 = weights_buf_12_ce0_local;

assign weights_buf_12_d0 = input_weights_load;

assign weights_buf_12_we0 = weights_buf_12_we0_local;

assign weights_buf_13_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_13_ce0 = weights_buf_13_ce0_local;

assign weights_buf_13_d0 = input_weights_load;

assign weights_buf_13_we0 = weights_buf_13_we0_local;

assign weights_buf_14_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_14_ce0 = weights_buf_14_ce0_local;

assign weights_buf_14_d0 = input_weights_load;

assign weights_buf_14_we0 = weights_buf_14_we0_local;

assign weights_buf_15_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_15_ce0 = weights_buf_15_ce0_local;

assign weights_buf_15_d0 = input_weights_load;

assign weights_buf_15_we0 = weights_buf_15_we0_local;

assign weights_buf_16_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_16_ce0 = weights_buf_16_ce0_local;

assign weights_buf_16_d0 = input_weights_load;

assign weights_buf_16_we0 = weights_buf_16_we0_local;

assign weights_buf_17_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_17_ce0 = weights_buf_17_ce0_local;

assign weights_buf_17_d0 = input_weights_load;

assign weights_buf_17_we0 = weights_buf_17_we0_local;

assign weights_buf_18_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_18_ce0 = weights_buf_18_ce0_local;

assign weights_buf_18_d0 = input_weights_load;

assign weights_buf_18_we0 = weights_buf_18_we0_local;

assign weights_buf_19_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_19_ce0 = weights_buf_19_ce0_local;

assign weights_buf_19_d0 = input_weights_load;

assign weights_buf_19_we0 = weights_buf_19_we0_local;

assign weights_buf_1_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_1_ce0 = weights_buf_1_ce0_local;

assign weights_buf_1_d0 = input_weights_load;

assign weights_buf_1_we0 = weights_buf_1_we0_local;

assign weights_buf_20_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_20_ce0 = weights_buf_20_ce0_local;

assign weights_buf_20_d0 = input_weights_load;

assign weights_buf_20_we0 = weights_buf_20_we0_local;

assign weights_buf_21_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_21_ce0 = weights_buf_21_ce0_local;

assign weights_buf_21_d0 = input_weights_load;

assign weights_buf_21_we0 = weights_buf_21_we0_local;

assign weights_buf_22_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_22_ce0 = weights_buf_22_ce0_local;

assign weights_buf_22_d0 = input_weights_load;

assign weights_buf_22_we0 = weights_buf_22_we0_local;

assign weights_buf_23_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_23_ce0 = weights_buf_23_ce0_local;

assign weights_buf_23_d0 = input_weights_load;

assign weights_buf_23_we0 = weights_buf_23_we0_local;

assign weights_buf_24_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_24_ce0 = weights_buf_24_ce0_local;

assign weights_buf_24_d0 = input_weights_load;

assign weights_buf_24_we0 = weights_buf_24_we0_local;

assign weights_buf_25_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_25_ce0 = weights_buf_25_ce0_local;

assign weights_buf_25_d0 = input_weights_load;

assign weights_buf_25_we0 = weights_buf_25_we0_local;

assign weights_buf_26_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_26_ce0 = weights_buf_26_ce0_local;

assign weights_buf_26_d0 = input_weights_load;

assign weights_buf_26_we0 = weights_buf_26_we0_local;

assign weights_buf_27_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_27_ce0 = weights_buf_27_ce0_local;

assign weights_buf_27_d0 = input_weights_load;

assign weights_buf_27_we0 = weights_buf_27_we0_local;

assign weights_buf_28_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_28_ce0 = weights_buf_28_ce0_local;

assign weights_buf_28_d0 = input_weights_load;

assign weights_buf_28_we0 = weights_buf_28_we0_local;

assign weights_buf_29_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_29_ce0 = weights_buf_29_ce0_local;

assign weights_buf_29_d0 = input_weights_load;

assign weights_buf_29_we0 = weights_buf_29_we0_local;

assign weights_buf_2_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_2_ce0 = weights_buf_2_ce0_local;

assign weights_buf_2_d0 = input_weights_load;

assign weights_buf_2_we0 = weights_buf_2_we0_local;

assign weights_buf_30_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_30_ce0 = weights_buf_30_ce0_local;

assign weights_buf_30_d0 = input_weights_load;

assign weights_buf_30_we0 = weights_buf_30_we0_local;

assign weights_buf_31_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_31_ce0 = weights_buf_31_ce0_local;

assign weights_buf_31_d0 = input_weights_load;

assign weights_buf_31_we0 = weights_buf_31_we0_local;

assign weights_buf_32_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_32_ce0 = weights_buf_32_ce0_local;

assign weights_buf_32_d0 = input_weights_load;

assign weights_buf_32_we0 = weights_buf_32_we0_local;

assign weights_buf_33_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_33_ce0 = weights_buf_33_ce0_local;

assign weights_buf_33_d0 = input_weights_load;

assign weights_buf_33_we0 = weights_buf_33_we0_local;

assign weights_buf_34_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_34_ce0 = weights_buf_34_ce0_local;

assign weights_buf_34_d0 = input_weights_load;

assign weights_buf_34_we0 = weights_buf_34_we0_local;

assign weights_buf_35_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_35_ce0 = weights_buf_35_ce0_local;

assign weights_buf_35_d0 = input_weights_load;

assign weights_buf_35_we0 = weights_buf_35_we0_local;

assign weights_buf_36_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_36_ce0 = weights_buf_36_ce0_local;

assign weights_buf_36_d0 = input_weights_load;

assign weights_buf_36_we0 = weights_buf_36_we0_local;

assign weights_buf_37_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_37_ce0 = weights_buf_37_ce0_local;

assign weights_buf_37_d0 = input_weights_load;

assign weights_buf_37_we0 = weights_buf_37_we0_local;

assign weights_buf_38_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_38_ce0 = weights_buf_38_ce0_local;

assign weights_buf_38_d0 = input_weights_load;

assign weights_buf_38_we0 = weights_buf_38_we0_local;

assign weights_buf_39_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_39_ce0 = weights_buf_39_ce0_local;

assign weights_buf_39_d0 = input_weights_load;

assign weights_buf_39_we0 = weights_buf_39_we0_local;

assign weights_buf_3_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_3_ce0 = weights_buf_3_ce0_local;

assign weights_buf_3_d0 = input_weights_load;

assign weights_buf_3_we0 = weights_buf_3_we0_local;

assign weights_buf_40_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_40_ce0 = weights_buf_40_ce0_local;

assign weights_buf_40_d0 = input_weights_load;

assign weights_buf_40_we0 = weights_buf_40_we0_local;

assign weights_buf_41_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_41_ce0 = weights_buf_41_ce0_local;

assign weights_buf_41_d0 = input_weights_load;

assign weights_buf_41_we0 = weights_buf_41_we0_local;

assign weights_buf_42_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_42_ce0 = weights_buf_42_ce0_local;

assign weights_buf_42_d0 = input_weights_load;

assign weights_buf_42_we0 = weights_buf_42_we0_local;

assign weights_buf_43_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_43_ce0 = weights_buf_43_ce0_local;

assign weights_buf_43_d0 = input_weights_load;

assign weights_buf_43_we0 = weights_buf_43_we0_local;

assign weights_buf_44_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_44_ce0 = weights_buf_44_ce0_local;

assign weights_buf_44_d0 = input_weights_load;

assign weights_buf_44_we0 = weights_buf_44_we0_local;

assign weights_buf_45_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_45_ce0 = weights_buf_45_ce0_local;

assign weights_buf_45_d0 = input_weights_load;

assign weights_buf_45_we0 = weights_buf_45_we0_local;

assign weights_buf_46_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_46_ce0 = weights_buf_46_ce0_local;

assign weights_buf_46_d0 = input_weights_load;

assign weights_buf_46_we0 = weights_buf_46_we0_local;

assign weights_buf_47_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_47_ce0 = weights_buf_47_ce0_local;

assign weights_buf_47_d0 = input_weights_load;

assign weights_buf_47_we0 = weights_buf_47_we0_local;

assign weights_buf_48_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_48_ce0 = weights_buf_48_ce0_local;

assign weights_buf_48_d0 = input_weights_load;

assign weights_buf_48_we0 = weights_buf_48_we0_local;

assign weights_buf_49_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_49_ce0 = weights_buf_49_ce0_local;

assign weights_buf_49_d0 = input_weights_load;

assign weights_buf_49_we0 = weights_buf_49_we0_local;

assign weights_buf_4_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_4_ce0 = weights_buf_4_ce0_local;

assign weights_buf_4_d0 = input_weights_load;

assign weights_buf_4_we0 = weights_buf_4_we0_local;

assign weights_buf_50_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_50_ce0 = weights_buf_50_ce0_local;

assign weights_buf_50_d0 = input_weights_load;

assign weights_buf_50_we0 = weights_buf_50_we0_local;

assign weights_buf_51_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_51_ce0 = weights_buf_51_ce0_local;

assign weights_buf_51_d0 = input_weights_load;

assign weights_buf_51_we0 = weights_buf_51_we0_local;

assign weights_buf_52_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_52_ce0 = weights_buf_52_ce0_local;

assign weights_buf_52_d0 = input_weights_load;

assign weights_buf_52_we0 = weights_buf_52_we0_local;

assign weights_buf_53_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_53_ce0 = weights_buf_53_ce0_local;

assign weights_buf_53_d0 = input_weights_load;

assign weights_buf_53_we0 = weights_buf_53_we0_local;

assign weights_buf_54_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_54_ce0 = weights_buf_54_ce0_local;

assign weights_buf_54_d0 = input_weights_load;

assign weights_buf_54_we0 = weights_buf_54_we0_local;

assign weights_buf_55_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_55_ce0 = weights_buf_55_ce0_local;

assign weights_buf_55_d0 = input_weights_load;

assign weights_buf_55_we0 = weights_buf_55_we0_local;

assign weights_buf_56_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_56_ce0 = weights_buf_56_ce0_local;

assign weights_buf_56_d0 = input_weights_load;

assign weights_buf_56_we0 = weights_buf_56_we0_local;

assign weights_buf_57_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_57_ce0 = weights_buf_57_ce0_local;

assign weights_buf_57_d0 = input_weights_load;

assign weights_buf_57_we0 = weights_buf_57_we0_local;

assign weights_buf_58_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_58_ce0 = weights_buf_58_ce0_local;

assign weights_buf_58_d0 = input_weights_load;

assign weights_buf_58_we0 = weights_buf_58_we0_local;

assign weights_buf_59_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_59_ce0 = weights_buf_59_ce0_local;

assign weights_buf_59_d0 = input_weights_load;

assign weights_buf_59_we0 = weights_buf_59_we0_local;

assign weights_buf_5_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_5_ce0 = weights_buf_5_ce0_local;

assign weights_buf_5_d0 = input_weights_load;

assign weights_buf_5_we0 = weights_buf_5_we0_local;

assign weights_buf_60_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_60_ce0 = weights_buf_60_ce0_local;

assign weights_buf_60_d0 = input_weights_load;

assign weights_buf_60_we0 = weights_buf_60_we0_local;

assign weights_buf_61_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_61_ce0 = weights_buf_61_ce0_local;

assign weights_buf_61_d0 = input_weights_load;

assign weights_buf_61_we0 = weights_buf_61_we0_local;

assign weights_buf_62_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_62_ce0 = weights_buf_62_ce0_local;

assign weights_buf_62_d0 = input_weights_load;

assign weights_buf_62_we0 = weights_buf_62_we0_local;

assign weights_buf_63_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_63_ce0 = weights_buf_63_ce0_local;

assign weights_buf_63_d0 = input_weights_load;

assign weights_buf_63_we0 = weights_buf_63_we0_local;

assign weights_buf_6_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_6_ce0 = weights_buf_6_ce0_local;

assign weights_buf_6_d0 = input_weights_load;

assign weights_buf_6_we0 = weights_buf_6_we0_local;

assign weights_buf_7_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_7_ce0 = weights_buf_7_ce0_local;

assign weights_buf_7_d0 = input_weights_load;

assign weights_buf_7_we0 = weights_buf_7_we0_local;

assign weights_buf_8_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_8_ce0 = weights_buf_8_ce0_local;

assign weights_buf_8_d0 = input_weights_load;

assign weights_buf_8_we0 = weights_buf_8_we0_local;

assign weights_buf_9_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_9_ce0 = weights_buf_9_ce0_local;

assign weights_buf_9_d0 = input_weights_load;

assign weights_buf_9_we0 = weights_buf_9_we0_local;

assign weights_buf_address0 = zext_ln74_1_fu_1242_p1;

assign weights_buf_ce0 = weights_buf_ce0_local;

assign weights_buf_d0 = input_weights_load;

assign weights_buf_we0 = weights_buf_we0_local;

assign zext_ln74_1_fu_1242_p1 = lshr_ln_fu_1232_p4;

assign zext_ln74_fu_1212_p1 = ap_sig_allocacmp_i;

endmodule //dequantize_nf4_q2_6_dequantize_nf4_q2_6_Pipeline_VITIS_LOOP_74_3
