// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mmult_accel_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        localA_15,
        localA_14,
        localA_13,
        localA_12,
        localA_11,
        localA_10,
        localA_9,
        localA_8,
        localA_7,
        localA_6,
        localA_5,
        localA_4,
        localA_3,
        localA_2,
        localA_1,
        localA,
        i0,
        current_block_M_A,
        k0,
        A_bram_address0,
        A_bram_ce0,
        A_bram_q0,
        K,
        localA_31_out,
        localA_31_out_ap_vld,
        localA_30_out,
        localA_30_out_ap_vld,
        localA_29_out,
        localA_29_out_ap_vld,
        localA_28_out,
        localA_28_out_ap_vld,
        localA_27_out,
        localA_27_out_ap_vld,
        localA_26_out,
        localA_26_out_ap_vld,
        localA_25_out,
        localA_25_out_ap_vld,
        localA_24_out,
        localA_24_out_ap_vld,
        localA_23_out,
        localA_23_out_ap_vld,
        localA_22_out,
        localA_22_out_ap_vld,
        localA_21_out,
        localA_21_out_ap_vld,
        localA_20_out,
        localA_20_out_ap_vld,
        localA_19_out,
        localA_19_out_ap_vld,
        localA_18_out,
        localA_18_out_ap_vld,
        localA_17_out,
        localA_17_out_ap_vld,
        localA_16_out,
        localA_16_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] localA_15;
input  [63:0] localA_14;
input  [63:0] localA_13;
input  [63:0] localA_12;
input  [63:0] localA_11;
input  [63:0] localA_10;
input  [63:0] localA_9;
input  [63:0] localA_8;
input  [63:0] localA_7;
input  [63:0] localA_6;
input  [63:0] localA_5;
input  [63:0] localA_4;
input  [63:0] localA_3;
input  [63:0] localA_2;
input  [63:0] localA_1;
input  [63:0] localA;
input  [30:0] i0;
input  [31:0] current_block_M_A;
input  [30:0] k0;
output  [14:0] A_bram_address0;
output   A_bram_ce0;
input  [7:0] A_bram_q0;
input  [31:0] K;
output  [63:0] localA_31_out;
output   localA_31_out_ap_vld;
output  [63:0] localA_30_out;
output   localA_30_out_ap_vld;
output  [63:0] localA_29_out;
output   localA_29_out_ap_vld;
output  [63:0] localA_28_out;
output   localA_28_out_ap_vld;
output  [63:0] localA_27_out;
output   localA_27_out_ap_vld;
output  [63:0] localA_26_out;
output   localA_26_out_ap_vld;
output  [63:0] localA_25_out;
output   localA_25_out_ap_vld;
output  [63:0] localA_24_out;
output   localA_24_out_ap_vld;
output  [63:0] localA_23_out;
output   localA_23_out_ap_vld;
output  [63:0] localA_22_out;
output   localA_22_out_ap_vld;
output  [63:0] localA_21_out;
output   localA_21_out_ap_vld;
output  [63:0] localA_20_out;
output   localA_20_out_ap_vld;
output  [63:0] localA_19_out;
output   localA_19_out_ap_vld;
output  [63:0] localA_18_out;
output   localA_18_out_ap_vld;
output  [63:0] localA_17_out;
output   localA_17_out_ap_vld;
output  [63:0] localA_16_out;
output   localA_16_out_ap_vld;

reg ap_idle;
reg localA_31_out_ap_vld;
reg localA_30_out_ap_vld;
reg localA_29_out_ap_vld;
reg localA_28_out_ap_vld;
reg localA_27_out_ap_vld;
reg localA_26_out_ap_vld;
reg localA_25_out_ap_vld;
reg localA_24_out_ap_vld;
reg localA_23_out_ap_vld;
reg localA_22_out_ap_vld;
reg localA_21_out_ap_vld;
reg localA_20_out_ap_vld;
reg localA_19_out_ap_vld;
reg localA_18_out_ap_vld;
reg localA_17_out_ap_vld;
reg localA_16_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln253_fu_571_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] k0_cast_fu_465_p1;
reg   [31:0] k0_cast_reg_1014;
wire   [31:0] i0_cast_fu_469_p1;
reg   [31:0] i0_cast_reg_1019;
reg   [0:0] icmp_ln253_reg_1024;
reg   [0:0] icmp_ln253_reg_1024_pp0_iter1_reg;
reg   [0:0] icmp_ln253_reg_1024_pp0_iter2_reg;
reg   [0:0] icmp_ln253_reg_1024_pp0_iter3_reg;
wire   [2:0] select_ln213_fu_606_p3;
reg   [2:0] select_ln213_reg_1028;
wire   [2:0] select_ln253_fu_614_p3;
reg   [2:0] select_ln253_reg_1033;
wire   [1:0] trunc_ln253_fu_622_p1;
reg   [1:0] trunc_ln253_reg_1038;
reg   [1:0] trunc_ln253_reg_1038_pp0_iter2_reg;
reg   [1:0] trunc_ln253_reg_1038_pp0_iter3_reg;
reg   [1:0] trunc_ln253_reg_1038_pp0_iter4_reg;
wire   [1:0] trunc_ln254_fu_626_p1;
reg   [1:0] trunc_ln254_reg_1042;
reg   [1:0] trunc_ln254_reg_1042_pp0_iter2_reg;
reg   [1:0] trunc_ln254_reg_1042_pp0_iter3_reg;
reg   [1:0] trunc_ln254_reg_1042_pp0_iter4_reg;
reg   [14:0] A_bram_addr_reg_1046;
wire   [0:0] and_ln258_fu_717_p2;
reg   [0:0] and_ln258_reg_1051;
reg   [0:0] and_ln258_reg_1051_pp0_iter3_reg;
wire   [7:0] ap_phi_reg_pp0_iter0_localA_32_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter1_localA_32_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter2_localA_32_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter3_localA_32_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter4_localA_32_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter5_localA_32_reg_454;
wire   [63:0] zext_ln259_fu_707_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] kk_fu_134;
wire   [2:0] add_ln254_fu_630_p2;
wire    ap_loop_init;
reg   [2:0] ii_fu_138;
reg   [4:0] indvar_flatten19_fu_142;
wire   [4:0] add_ln253_1_fu_577_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten19_load;
reg   [63:0] localA_16_fu_146;
wire  signed [63:0] localA_48_cast_fu_723_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [63:0] localA_17_fu_150;
reg   [63:0] localA_18_fu_154;
reg   [63:0] localA_19_fu_158;
reg   [63:0] localA_20_fu_162;
reg   [63:0] localA_21_fu_166;
reg   [63:0] localA_22_fu_170;
reg   [63:0] localA_23_fu_174;
reg   [63:0] localA_24_fu_178;
reg   [63:0] localA_25_fu_182;
reg   [63:0] localA_26_fu_186;
reg   [63:0] localA_27_fu_190;
reg   [63:0] localA_28_fu_194;
reg   [63:0] localA_29_fu_198;
reg   [63:0] localA_30_fu_202;
reg   [63:0] localA_31_fu_206;
wire    ap_block_pp0_stage0_01001;
reg    A_bram_ce0_local;
wire   [0:0] icmp_ln254_fu_600_p2;
wire   [2:0] add_ln253_fu_594_p2;
wire   [31:0] zext_ln253_fu_646_p1;
wire   [31:0] empty_fu_649_p2;
wire   [4:0] trunc_ln259_fu_654_p1;
wire   [6:0] trunc_ln259_1_fu_666_p1;
wire   [14:0] p_shl_fu_658_p3;
wire   [14:0] p_shl1_fu_670_p3;
wire   [31:0] zext_ln254_fu_689_p1;
wire   [31:0] add_ln257_fu_692_p2;
wire   [14:0] sub_ln259_fu_678_p2;
wire   [14:0] trunc_ln259_2_fu_697_p1;
wire   [14:0] add_ln259_fu_701_p2;
wire   [0:0] cmp135_fu_684_p2;
wire   [0:0] icmp_ln258_fu_712_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_611;
reg    ap_condition_615;
reg    ap_condition_619;
reg    ap_condition_623;
reg    ap_condition_626;
reg    ap_condition_629;
reg    ap_condition_632;
reg    ap_condition_635;
reg    ap_condition_638;
reg    ap_condition_641;
reg    ap_condition_644;
reg    ap_condition_647;
reg    ap_condition_650;
reg    ap_condition_653;
reg    ap_condition_656;
reg    ap_condition_659;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 kk_fu_134 = 3'd0;
#0 ii_fu_138 = 3'd0;
#0 indvar_flatten19_fu_142 = 5'd0;
#0 localA_16_fu_146 = 64'd0;
#0 localA_17_fu_150 = 64'd0;
#0 localA_18_fu_154 = 64'd0;
#0 localA_19_fu_158 = 64'd0;
#0 localA_20_fu_162 = 64'd0;
#0 localA_21_fu_166 = 64'd0;
#0 localA_22_fu_170 = 64'd0;
#0 localA_23_fu_174 = 64'd0;
#0 localA_24_fu_178 = 64'd0;
#0 localA_25_fu_182 = 64'd0;
#0 localA_26_fu_186 = 64'd0;
#0 localA_27_fu_190 = 64'd0;
#0 localA_28_fu_194 = 64'd0;
#0 localA_29_fu_198 = 64'd0;
#0 localA_30_fu_202 = 64'd0;
#0 localA_31_fu_206 = 64'd0;
#0 ap_done_reg = 1'b0;
end

mmult_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((1'd0 == and_ln258_reg_1051) & (icmp_ln253_reg_1024_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_localA_32_reg_454 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_localA_32_reg_454 <= ap_phi_reg_pp0_iter3_localA_32_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if (((1'd1 == and_ln258_reg_1051_pp0_iter3_reg) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter5_localA_32_reg_454 <= A_bram_q0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter5_localA_32_reg_454 <= ap_phi_reg_pp0_iter4_localA_32_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ii_fu_138 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ii_fu_138 <= select_ln253_fu_614_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln253_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten19_fu_142 <= add_ln253_1_fu_577_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_142 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            kk_fu_134 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            kk_fu_134 <= add_ln254_fu_630_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_16_fu_146 <= localA;
        end else if ((1'b1 == ap_condition_611)) begin
            localA_16_fu_146 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_17_fu_150 <= localA_1;
        end else if ((1'b1 == ap_condition_615)) begin
            localA_17_fu_150 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_18_fu_154 <= localA_2;
        end else if ((1'b1 == ap_condition_619)) begin
            localA_18_fu_154 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_19_fu_158 <= localA_3;
        end else if ((1'b1 == ap_condition_623)) begin
            localA_19_fu_158 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_20_fu_162 <= localA_4;
        end else if ((1'b1 == ap_condition_626)) begin
            localA_20_fu_162 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_21_fu_166 <= localA_5;
        end else if ((1'b1 == ap_condition_629)) begin
            localA_21_fu_166 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_22_fu_170 <= localA_6;
        end else if ((1'b1 == ap_condition_632)) begin
            localA_22_fu_170 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_23_fu_174 <= localA_7;
        end else if ((1'b1 == ap_condition_635)) begin
            localA_23_fu_174 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_24_fu_178 <= localA_8;
        end else if ((1'b1 == ap_condition_638)) begin
            localA_24_fu_178 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_25_fu_182 <= localA_9;
        end else if ((1'b1 == ap_condition_641)) begin
            localA_25_fu_182 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_26_fu_186 <= localA_10;
        end else if ((1'b1 == ap_condition_644)) begin
            localA_26_fu_186 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_27_fu_190 <= localA_11;
        end else if ((1'b1 == ap_condition_647)) begin
            localA_27_fu_190 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_28_fu_194 <= localA_12;
        end else if ((1'b1 == ap_condition_650)) begin
            localA_28_fu_194 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_29_fu_198 <= localA_13;
        end else if ((1'b1 == ap_condition_653)) begin
            localA_29_fu_198 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_30_fu_202 <= localA_14;
        end else if ((1'b1 == ap_condition_656)) begin
            localA_30_fu_202 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            localA_31_fu_206 <= localA_15;
        end else if ((1'b1 == ap_condition_659)) begin
            localA_31_fu_206 <= localA_48_cast_fu_723_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        A_bram_addr_reg_1046 <= zext_ln259_fu_707_p1;
        and_ln258_reg_1051 <= and_ln258_fu_717_p2;
        and_ln258_reg_1051_pp0_iter3_reg <= and_ln258_reg_1051;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln253_reg_1024_pp0_iter2_reg <= icmp_ln253_reg_1024_pp0_iter1_reg;
        icmp_ln253_reg_1024_pp0_iter3_reg <= icmp_ln253_reg_1024_pp0_iter2_reg;
        trunc_ln253_reg_1038_pp0_iter2_reg <= trunc_ln253_reg_1038;
        trunc_ln253_reg_1038_pp0_iter3_reg <= trunc_ln253_reg_1038_pp0_iter2_reg;
        trunc_ln253_reg_1038_pp0_iter4_reg <= trunc_ln253_reg_1038_pp0_iter3_reg;
        trunc_ln254_reg_1042_pp0_iter2_reg <= trunc_ln254_reg_1042;
        trunc_ln254_reg_1042_pp0_iter3_reg <= trunc_ln254_reg_1042_pp0_iter2_reg;
        trunc_ln254_reg_1042_pp0_iter4_reg <= trunc_ln254_reg_1042_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i0_cast_reg_1019[30 : 0] <= i0_cast_fu_469_p1[30 : 0];
        icmp_ln253_reg_1024 <= icmp_ln253_fu_571_p2;
        icmp_ln253_reg_1024_pp0_iter1_reg <= icmp_ln253_reg_1024;
        k0_cast_reg_1014[30 : 0] <= k0_cast_fu_465_p1[30 : 0];
        select_ln213_reg_1028 <= select_ln213_fu_606_p3;
        select_ln253_reg_1033 <= select_ln253_fu_614_p3;
        trunc_ln253_reg_1038 <= trunc_ln253_fu_622_p1;
        trunc_ln254_reg_1042 <= trunc_ln254_fu_626_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_localA_32_reg_454 <= ap_phi_reg_pp0_iter0_localA_32_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_localA_32_reg_454 <= ap_phi_reg_pp0_iter1_localA_32_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_localA_32_reg_454 <= ap_phi_reg_pp0_iter2_localA_32_reg_454;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        A_bram_ce0_local = 1'b1;
    end else begin
        A_bram_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln253_fu_571_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten19_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten19_load = indvar_flatten19_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_16_out_ap_vld = 1'b1;
    end else begin
        localA_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_17_out_ap_vld = 1'b1;
    end else begin
        localA_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_18_out_ap_vld = 1'b1;
    end else begin
        localA_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_19_out_ap_vld = 1'b1;
    end else begin
        localA_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_20_out_ap_vld = 1'b1;
    end else begin
        localA_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_21_out_ap_vld = 1'b1;
    end else begin
        localA_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_22_out_ap_vld = 1'b1;
    end else begin
        localA_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_23_out_ap_vld = 1'b1;
    end else begin
        localA_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_24_out_ap_vld = 1'b1;
    end else begin
        localA_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_25_out_ap_vld = 1'b1;
    end else begin
        localA_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_26_out_ap_vld = 1'b1;
    end else begin
        localA_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_27_out_ap_vld = 1'b1;
    end else begin
        localA_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_28_out_ap_vld = 1'b1;
    end else begin
        localA_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_29_out_ap_vld = 1'b1;
    end else begin
        localA_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_30_out_ap_vld = 1'b1;
    end else begin
        localA_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln253_reg_1024_pp0_iter3_reg == 1'd1))) begin
        localA_31_out_ap_vld = 1'b1;
    end else begin
        localA_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_bram_address0 = A_bram_addr_reg_1046;

assign A_bram_ce0 = A_bram_ce0_local;

assign add_ln253_1_fu_577_p2 = (ap_sig_allocacmp_indvar_flatten19_load + 5'd1);

assign add_ln253_fu_594_p2 = (ii_fu_138 + 3'd1);

assign add_ln254_fu_630_p2 = (select_ln213_fu_606_p3 + 3'd1);

assign add_ln257_fu_692_p2 = (zext_ln254_fu_689_p1 + k0_cast_reg_1014);

assign add_ln259_fu_701_p2 = (sub_ln259_fu_678_p2 + trunc_ln259_2_fu_697_p1);

assign and_ln258_fu_717_p2 = (icmp_ln258_fu_712_p2 & cmp135_fu_684_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_611 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd0) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd0));
end

always @ (*) begin
    ap_condition_615 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd1) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd0));
end

always @ (*) begin
    ap_condition_619 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd2) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd0));
end

always @ (*) begin
    ap_condition_623 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd3) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd0));
end

always @ (*) begin
    ap_condition_626 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd0) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd1));
end

always @ (*) begin
    ap_condition_629 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd1) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd1));
end

always @ (*) begin
    ap_condition_632 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd2) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd1));
end

always @ (*) begin
    ap_condition_635 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd3) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd1));
end

always @ (*) begin
    ap_condition_638 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd0) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd2));
end

always @ (*) begin
    ap_condition_641 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd1) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd2));
end

always @ (*) begin
    ap_condition_644 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd2) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd2));
end

always @ (*) begin
    ap_condition_647 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd3) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd2));
end

always @ (*) begin
    ap_condition_650 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd0) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd3));
end

always @ (*) begin
    ap_condition_653 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd1) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd3));
end

always @ (*) begin
    ap_condition_656 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd2) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd3));
end

always @ (*) begin
    ap_condition_659 = ((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln254_reg_1042_pp0_iter4_reg == 2'd3) & (trunc_ln253_reg_1038_pp0_iter4_reg == 2'd3));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_localA_32_reg_454 = 'bx;

assign ap_ready = ap_ready_sig;

assign cmp135_fu_684_p2 = (($signed(empty_fu_649_p2) < $signed(current_block_M_A)) ? 1'b1 : 1'b0);

assign empty_fu_649_p2 = (zext_ln253_fu_646_p1 + i0_cast_reg_1019);

assign i0_cast_fu_469_p1 = i0;

assign icmp_ln253_fu_571_p2 = ((ap_sig_allocacmp_indvar_flatten19_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln254_fu_600_p2 = ((kk_fu_134 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln258_fu_712_p2 = (($signed(add_ln257_fu_692_p2) < $signed(K)) ? 1'b1 : 1'b0);

assign k0_cast_fu_465_p1 = k0;

assign localA_16_out = localA_16_fu_146;

assign localA_17_out = localA_17_fu_150;

assign localA_18_out = localA_18_fu_154;

assign localA_19_out = localA_19_fu_158;

assign localA_20_out = localA_20_fu_162;

assign localA_21_out = localA_21_fu_166;

assign localA_22_out = localA_22_fu_170;

assign localA_23_out = localA_23_fu_174;

assign localA_24_out = localA_24_fu_178;

assign localA_25_out = localA_25_fu_182;

assign localA_26_out = localA_26_fu_186;

assign localA_27_out = localA_27_fu_190;

assign localA_28_out = localA_28_fu_194;

assign localA_29_out = localA_29_fu_198;

assign localA_30_out = localA_30_fu_202;

assign localA_31_out = localA_31_fu_206;

assign localA_48_cast_fu_723_p1 = $signed(ap_phi_reg_pp0_iter5_localA_32_reg_454);

assign p_shl1_fu_670_p3 = {{trunc_ln259_1_fu_666_p1}, {8'd0}};

assign p_shl_fu_658_p3 = {{trunc_ln259_fu_654_p1}, {10'd0}};

assign select_ln213_fu_606_p3 = ((icmp_ln254_fu_600_p2[0:0] == 1'b1) ? 3'd0 : kk_fu_134);

assign select_ln253_fu_614_p3 = ((icmp_ln254_fu_600_p2[0:0] == 1'b1) ? add_ln253_fu_594_p2 : ii_fu_138);

assign sub_ln259_fu_678_p2 = (p_shl_fu_658_p3 - p_shl1_fu_670_p3);

assign trunc_ln253_fu_622_p1 = select_ln253_fu_614_p3[1:0];

assign trunc_ln254_fu_626_p1 = select_ln213_fu_606_p3[1:0];

assign trunc_ln259_1_fu_666_p1 = empty_fu_649_p2[6:0];

assign trunc_ln259_2_fu_697_p1 = add_ln257_fu_692_p2[14:0];

assign trunc_ln259_fu_654_p1 = empty_fu_649_p2[4:0];

assign zext_ln253_fu_646_p1 = select_ln253_reg_1033;

assign zext_ln254_fu_689_p1 = select_ln213_reg_1028;

assign zext_ln259_fu_707_p1 = add_ln259_fu_701_p2;

always @ (posedge ap_clk) begin
    k0_cast_reg_1014[31] <= 1'b0;
    i0_cast_reg_1019[31] <= 1'b0;
end

endmodule //mmult_accel_mmult_accel_Pipeline_loadA_VITIS_LOOP_254_6
