// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module quantize_nf4_q2_6_quantize_nf4_q2_6_Pipeline_VITIS_LOOP_114_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty,
        q1_constants,
        q1_constants_1,
        q1_constants_2,
        q1_constants_3,
        q1_constants_4,
        q1_constants_5,
        q1_constants_6,
        q1_constants_7,
        q1_constants_8,
        q1_constants_9,
        q1_constants_10,
        q1_constants_11,
        q1_constants_12,
        q1_constants_13,
        q1_constants_14,
        q1_constants_15,
        q1_constants_16,
        q1_constants_17,
        q1_constants_18,
        q1_constants_19,
        q1_constants_20,
        q1_constants_21,
        q1_constants_22,
        q1_constants_23,
        q1_constants_24,
        q1_constants_25,
        q1_constants_26,
        q1_constants_27,
        q1_constants_28,
        q1_constants_29,
        q1_constants_30,
        q1_constants_31,
        q1_constants_32,
        q1_constants_33,
        q1_constants_34,
        q1_constants_35,
        q1_constants_36,
        q1_constants_37,
        q1_constants_38,
        q1_constants_39,
        q1_constants_40,
        q1_constants_41,
        q1_constants_42,
        q1_constants_43,
        q1_constants_44,
        q1_constants_45,
        q1_constants_46,
        q1_constants_47,
        q1_constants_48,
        q1_constants_49,
        q1_constants_50,
        q1_constants_51,
        q1_constants_52,
        q1_constants_53,
        q1_constants_54,
        q1_constants_55,
        q1_constants_56,
        q1_constants_57,
        q1_constants_58,
        q1_constants_59,
        q1_constants_60,
        q1_constants_61,
        q1_constants_62,
        q1_constants_63,
        q1_constants_64,
        q1_constants_65,
        q1_constants_66,
        q1_constants_67,
        q1_constants_68,
        q1_constants_69,
        q1_constants_70,
        q1_constants_71,
        q1_constants_72,
        q1_constants_73,
        q1_constants_74,
        q1_constants_75,
        q1_constants_76,
        q1_constants_77,
        q1_constants_78,
        q1_constants_79,
        q1_constants_80,
        q1_constants_81,
        q1_constants_82,
        q1_constants_83,
        q1_constants_84,
        q1_constants_85,
        q1_constants_86,
        q1_constants_87,
        q1_constants_88,
        q1_constants_89,
        q1_constants_90,
        q1_constants_91,
        q1_constants_92,
        q1_constants_93,
        q1_constants_94,
        q1_constants_95,
        q1_constants_96,
        q1_constants_97,
        q1_constants_98,
        q1_constants_99,
        q1_constants_100,
        q1_constants_101,
        q1_constants_102,
        q1_constants_103,
        q1_constants_104,
        q1_constants_105,
        q1_constants_106,
        q1_constants_107,
        q1_constants_108,
        q1_constants_109,
        q1_constants_110,
        q1_constants_111,
        q1_constants_112,
        q1_constants_113,
        q1_constants_114,
        q1_constants_115,
        q1_constants_116,
        q1_constants_117,
        q1_constants_118,
        q1_constants_119,
        q1_constants_120,
        q1_constants_121,
        q1_constants_122,
        q1_constants_123,
        q1_constants_124,
        q1_constants_125,
        q1_constants_126,
        q1_constants_127,
        q1_constants_128,
        q1_constants_129,
        q1_constants_130,
        q1_constants_131,
        q1_constants_132,
        q1_constants_133,
        q1_constants_134,
        q1_constants_135,
        q1_constants_136,
        q1_constants_137,
        q1_constants_138,
        q1_constants_139,
        q1_constants_140,
        q1_constants_141,
        q1_constants_142,
        q1_constants_143,
        q1_constants_144,
        q1_constants_145,
        q1_constants_146,
        q1_constants_147,
        q1_constants_148,
        q1_constants_149,
        q1_constants_150,
        q1_constants_151,
        q1_constants_152,
        q1_constants_153,
        q1_constants_154,
        q1_constants_155,
        q1_constants_156,
        q1_constants_157,
        q1_constants_158,
        q1_constants_159,
        q1_constants_160,
        q1_constants_161,
        q1_constants_162,
        q1_constants_163,
        q1_constants_164,
        q1_constants_165,
        q1_constants_166,
        q1_constants_167,
        q1_constants_168,
        q1_constants_169,
        q1_constants_170,
        q1_constants_171,
        q1_constants_172,
        q1_constants_173,
        q1_constants_174,
        q1_constants_175,
        q1_constants_176,
        q1_constants_177,
        q1_constants_178,
        q1_constants_179,
        q1_constants_180,
        q1_constants_181,
        q1_constants_182,
        q1_constants_183,
        q1_constants_184,
        q1_constants_185,
        q1_constants_186,
        q1_constants_187,
        q1_constants_188,
        q1_constants_189,
        q1_constants_190,
        q1_constants_191,
        q1_constants_192,
        q1_constants_193,
        q1_constants_194,
        q1_constants_195,
        q1_constants_196,
        q1_constants_197,
        q1_constants_198,
        q1_constants_199,
        q1_constants_200,
        q1_constants_201,
        q1_constants_202,
        q1_constants_203,
        q1_constants_204,
        q1_constants_205,
        q1_constants_206,
        q1_constants_207,
        q1_constants_208,
        q1_constants_209,
        q1_constants_210,
        q1_constants_211,
        q1_constants_212,
        q1_constants_213,
        q1_constants_214,
        q1_constants_215,
        q1_constants_216,
        q1_constants_217,
        q1_constants_218,
        q1_constants_219,
        q1_constants_220,
        q1_constants_221,
        q1_constants_222,
        q1_constants_223,
        q1_constants_224,
        q1_constants_225,
        q1_constants_226,
        q1_constants_227,
        q1_constants_228,
        q1_constants_229,
        q1_constants_230,
        q1_constants_231,
        q1_constants_232,
        q1_constants_233,
        q1_constants_234,
        q1_constants_235,
        q1_constants_236,
        q1_constants_237,
        q1_constants_238,
        q1_constants_239,
        q1_constants_240,
        q1_constants_241,
        q1_constants_242,
        q1_constants_243,
        q1_constants_244,
        q1_constants_245,
        q1_constants_246,
        q1_constants_247,
        q1_constants_248,
        q1_constants_249,
        q1_constants_250,
        q1_constants_251,
        q1_constants_252,
        q1_constants_253,
        q1_constants_254,
        q1_constants_255,
        max_q1_out,
        max_q1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] empty;
input  [7:0] q1_constants;
input  [7:0] q1_constants_1;
input  [7:0] q1_constants_2;
input  [7:0] q1_constants_3;
input  [7:0] q1_constants_4;
input  [7:0] q1_constants_5;
input  [7:0] q1_constants_6;
input  [7:0] q1_constants_7;
input  [7:0] q1_constants_8;
input  [7:0] q1_constants_9;
input  [7:0] q1_constants_10;
input  [7:0] q1_constants_11;
input  [7:0] q1_constants_12;
input  [7:0] q1_constants_13;
input  [7:0] q1_constants_14;
input  [7:0] q1_constants_15;
input  [7:0] q1_constants_16;
input  [7:0] q1_constants_17;
input  [7:0] q1_constants_18;
input  [7:0] q1_constants_19;
input  [7:0] q1_constants_20;
input  [7:0] q1_constants_21;
input  [7:0] q1_constants_22;
input  [7:0] q1_constants_23;
input  [7:0] q1_constants_24;
input  [7:0] q1_constants_25;
input  [7:0] q1_constants_26;
input  [7:0] q1_constants_27;
input  [7:0] q1_constants_28;
input  [7:0] q1_constants_29;
input  [7:0] q1_constants_30;
input  [7:0] q1_constants_31;
input  [7:0] q1_constants_32;
input  [7:0] q1_constants_33;
input  [7:0] q1_constants_34;
input  [7:0] q1_constants_35;
input  [7:0] q1_constants_36;
input  [7:0] q1_constants_37;
input  [7:0] q1_constants_38;
input  [7:0] q1_constants_39;
input  [7:0] q1_constants_40;
input  [7:0] q1_constants_41;
input  [7:0] q1_constants_42;
input  [7:0] q1_constants_43;
input  [7:0] q1_constants_44;
input  [7:0] q1_constants_45;
input  [7:0] q1_constants_46;
input  [7:0] q1_constants_47;
input  [7:0] q1_constants_48;
input  [7:0] q1_constants_49;
input  [7:0] q1_constants_50;
input  [7:0] q1_constants_51;
input  [7:0] q1_constants_52;
input  [7:0] q1_constants_53;
input  [7:0] q1_constants_54;
input  [7:0] q1_constants_55;
input  [7:0] q1_constants_56;
input  [7:0] q1_constants_57;
input  [7:0] q1_constants_58;
input  [7:0] q1_constants_59;
input  [7:0] q1_constants_60;
input  [7:0] q1_constants_61;
input  [7:0] q1_constants_62;
input  [7:0] q1_constants_63;
input  [7:0] q1_constants_64;
input  [7:0] q1_constants_65;
input  [7:0] q1_constants_66;
input  [7:0] q1_constants_67;
input  [7:0] q1_constants_68;
input  [7:0] q1_constants_69;
input  [7:0] q1_constants_70;
input  [7:0] q1_constants_71;
input  [7:0] q1_constants_72;
input  [7:0] q1_constants_73;
input  [7:0] q1_constants_74;
input  [7:0] q1_constants_75;
input  [7:0] q1_constants_76;
input  [7:0] q1_constants_77;
input  [7:0] q1_constants_78;
input  [7:0] q1_constants_79;
input  [7:0] q1_constants_80;
input  [7:0] q1_constants_81;
input  [7:0] q1_constants_82;
input  [7:0] q1_constants_83;
input  [7:0] q1_constants_84;
input  [7:0] q1_constants_85;
input  [7:0] q1_constants_86;
input  [7:0] q1_constants_87;
input  [7:0] q1_constants_88;
input  [7:0] q1_constants_89;
input  [7:0] q1_constants_90;
input  [7:0] q1_constants_91;
input  [7:0] q1_constants_92;
input  [7:0] q1_constants_93;
input  [7:0] q1_constants_94;
input  [7:0] q1_constants_95;
input  [7:0] q1_constants_96;
input  [7:0] q1_constants_97;
input  [7:0] q1_constants_98;
input  [7:0] q1_constants_99;
input  [7:0] q1_constants_100;
input  [7:0] q1_constants_101;
input  [7:0] q1_constants_102;
input  [7:0] q1_constants_103;
input  [7:0] q1_constants_104;
input  [7:0] q1_constants_105;
input  [7:0] q1_constants_106;
input  [7:0] q1_constants_107;
input  [7:0] q1_constants_108;
input  [7:0] q1_constants_109;
input  [7:0] q1_constants_110;
input  [7:0] q1_constants_111;
input  [7:0] q1_constants_112;
input  [7:0] q1_constants_113;
input  [7:0] q1_constants_114;
input  [7:0] q1_constants_115;
input  [7:0] q1_constants_116;
input  [7:0] q1_constants_117;
input  [7:0] q1_constants_118;
input  [7:0] q1_constants_119;
input  [7:0] q1_constants_120;
input  [7:0] q1_constants_121;
input  [7:0] q1_constants_122;
input  [7:0] q1_constants_123;
input  [7:0] q1_constants_124;
input  [7:0] q1_constants_125;
input  [7:0] q1_constants_126;
input  [7:0] q1_constants_127;
input  [7:0] q1_constants_128;
input  [7:0] q1_constants_129;
input  [7:0] q1_constants_130;
input  [7:0] q1_constants_131;
input  [7:0] q1_constants_132;
input  [7:0] q1_constants_133;
input  [7:0] q1_constants_134;
input  [7:0] q1_constants_135;
input  [7:0] q1_constants_136;
input  [7:0] q1_constants_137;
input  [7:0] q1_constants_138;
input  [7:0] q1_constants_139;
input  [7:0] q1_constants_140;
input  [7:0] q1_constants_141;
input  [7:0] q1_constants_142;
input  [7:0] q1_constants_143;
input  [7:0] q1_constants_144;
input  [7:0] q1_constants_145;
input  [7:0] q1_constants_146;
input  [7:0] q1_constants_147;
input  [7:0] q1_constants_148;
input  [7:0] q1_constants_149;
input  [7:0] q1_constants_150;
input  [7:0] q1_constants_151;
input  [7:0] q1_constants_152;
input  [7:0] q1_constants_153;
input  [7:0] q1_constants_154;
input  [7:0] q1_constants_155;
input  [7:0] q1_constants_156;
input  [7:0] q1_constants_157;
input  [7:0] q1_constants_158;
input  [7:0] q1_constants_159;
input  [7:0] q1_constants_160;
input  [7:0] q1_constants_161;
input  [7:0] q1_constants_162;
input  [7:0] q1_constants_163;
input  [7:0] q1_constants_164;
input  [7:0] q1_constants_165;
input  [7:0] q1_constants_166;
input  [7:0] q1_constants_167;
input  [7:0] q1_constants_168;
input  [7:0] q1_constants_169;
input  [7:0] q1_constants_170;
input  [7:0] q1_constants_171;
input  [7:0] q1_constants_172;
input  [7:0] q1_constants_173;
input  [7:0] q1_constants_174;
input  [7:0] q1_constants_175;
input  [7:0] q1_constants_176;
input  [7:0] q1_constants_177;
input  [7:0] q1_constants_178;
input  [7:0] q1_constants_179;
input  [7:0] q1_constants_180;
input  [7:0] q1_constants_181;
input  [7:0] q1_constants_182;
input  [7:0] q1_constants_183;
input  [7:0] q1_constants_184;
input  [7:0] q1_constants_185;
input  [7:0] q1_constants_186;
input  [7:0] q1_constants_187;
input  [7:0] q1_constants_188;
input  [7:0] q1_constants_189;
input  [7:0] q1_constants_190;
input  [7:0] q1_constants_191;
input  [7:0] q1_constants_192;
input  [7:0] q1_constants_193;
input  [7:0] q1_constants_194;
input  [7:0] q1_constants_195;
input  [7:0] q1_constants_196;
input  [7:0] q1_constants_197;
input  [7:0] q1_constants_198;
input  [7:0] q1_constants_199;
input  [7:0] q1_constants_200;
input  [7:0] q1_constants_201;
input  [7:0] q1_constants_202;
input  [7:0] q1_constants_203;
input  [7:0] q1_constants_204;
input  [7:0] q1_constants_205;
input  [7:0] q1_constants_206;
input  [7:0] q1_constants_207;
input  [7:0] q1_constants_208;
input  [7:0] q1_constants_209;
input  [7:0] q1_constants_210;
input  [7:0] q1_constants_211;
input  [7:0] q1_constants_212;
input  [7:0] q1_constants_213;
input  [7:0] q1_constants_214;
input  [7:0] q1_constants_215;
input  [7:0] q1_constants_216;
input  [7:0] q1_constants_217;
input  [7:0] q1_constants_218;
input  [7:0] q1_constants_219;
input  [7:0] q1_constants_220;
input  [7:0] q1_constants_221;
input  [7:0] q1_constants_222;
input  [7:0] q1_constants_223;
input  [7:0] q1_constants_224;
input  [7:0] q1_constants_225;
input  [7:0] q1_constants_226;
input  [7:0] q1_constants_227;
input  [7:0] q1_constants_228;
input  [7:0] q1_constants_229;
input  [7:0] q1_constants_230;
input  [7:0] q1_constants_231;
input  [7:0] q1_constants_232;
input  [7:0] q1_constants_233;
input  [7:0] q1_constants_234;
input  [7:0] q1_constants_235;
input  [7:0] q1_constants_236;
input  [7:0] q1_constants_237;
input  [7:0] q1_constants_238;
input  [7:0] q1_constants_239;
input  [7:0] q1_constants_240;
input  [7:0] q1_constants_241;
input  [7:0] q1_constants_242;
input  [7:0] q1_constants_243;
input  [7:0] q1_constants_244;
input  [7:0] q1_constants_245;
input  [7:0] q1_constants_246;
input  [7:0] q1_constants_247;
input  [7:0] q1_constants_248;
input  [7:0] q1_constants_249;
input  [7:0] q1_constants_250;
input  [7:0] q1_constants_251;
input  [7:0] q1_constants_252;
input  [7:0] q1_constants_253;
input  [7:0] q1_constants_254;
input  [7:0] q1_constants_255;
output  [7:0] max_q1_out;
output   max_q1_out_ap_vld;

reg ap_idle;
reg max_q1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln114_fu_2636_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] abs_q_fu_3698_p3;
reg   [7:0] abs_q_reg_3753;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] max_q1_fu_1066;
wire   [7:0] max_q1_1_fu_3719_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [8:0] i_fu_1070;
wire   [8:0] add_ln114_fu_2642_p2;
reg   [8:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] val_fu_2652_p513;
wire   [7:0] val_fu_2652_p514;
wire   [7:0] val_fu_2652_p515;
wire   [0:0] tmp_1_fu_3684_p3;
wire   [7:0] sub_ln24_fu_3692_p2;
wire   [0:0] icmp_ln117_fu_3714_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [7:0] val_fu_2652_p1;
wire   [7:0] val_fu_2652_p3;
wire   [7:0] val_fu_2652_p5;
wire   [7:0] val_fu_2652_p7;
wire   [7:0] val_fu_2652_p9;
wire   [7:0] val_fu_2652_p11;
wire   [7:0] val_fu_2652_p13;
wire   [7:0] val_fu_2652_p15;
wire   [7:0] val_fu_2652_p17;
wire   [7:0] val_fu_2652_p19;
wire   [7:0] val_fu_2652_p21;
wire   [7:0] val_fu_2652_p23;
wire   [7:0] val_fu_2652_p25;
wire   [7:0] val_fu_2652_p27;
wire   [7:0] val_fu_2652_p29;
wire   [7:0] val_fu_2652_p31;
wire   [7:0] val_fu_2652_p33;
wire   [7:0] val_fu_2652_p35;
wire   [7:0] val_fu_2652_p37;
wire   [7:0] val_fu_2652_p39;
wire   [7:0] val_fu_2652_p41;
wire   [7:0] val_fu_2652_p43;
wire   [7:0] val_fu_2652_p45;
wire   [7:0] val_fu_2652_p47;
wire   [7:0] val_fu_2652_p49;
wire   [7:0] val_fu_2652_p51;
wire   [7:0] val_fu_2652_p53;
wire   [7:0] val_fu_2652_p55;
wire   [7:0] val_fu_2652_p57;
wire   [7:0] val_fu_2652_p59;
wire   [7:0] val_fu_2652_p61;
wire   [7:0] val_fu_2652_p63;
wire   [7:0] val_fu_2652_p65;
wire   [7:0] val_fu_2652_p67;
wire   [7:0] val_fu_2652_p69;
wire   [7:0] val_fu_2652_p71;
wire   [7:0] val_fu_2652_p73;
wire   [7:0] val_fu_2652_p75;
wire   [7:0] val_fu_2652_p77;
wire   [7:0] val_fu_2652_p79;
wire   [7:0] val_fu_2652_p81;
wire   [7:0] val_fu_2652_p83;
wire   [7:0] val_fu_2652_p85;
wire   [7:0] val_fu_2652_p87;
wire   [7:0] val_fu_2652_p89;
wire   [7:0] val_fu_2652_p91;
wire   [7:0] val_fu_2652_p93;
wire   [7:0] val_fu_2652_p95;
wire   [7:0] val_fu_2652_p97;
wire   [7:0] val_fu_2652_p99;
wire   [7:0] val_fu_2652_p101;
wire   [7:0] val_fu_2652_p103;
wire   [7:0] val_fu_2652_p105;
wire   [7:0] val_fu_2652_p107;
wire   [7:0] val_fu_2652_p109;
wire   [7:0] val_fu_2652_p111;
wire   [7:0] val_fu_2652_p113;
wire   [7:0] val_fu_2652_p115;
wire   [7:0] val_fu_2652_p117;
wire   [7:0] val_fu_2652_p119;
wire   [7:0] val_fu_2652_p121;
wire   [7:0] val_fu_2652_p123;
wire   [7:0] val_fu_2652_p125;
wire   [7:0] val_fu_2652_p127;
wire   [7:0] val_fu_2652_p129;
wire   [7:0] val_fu_2652_p131;
wire   [7:0] val_fu_2652_p133;
wire   [7:0] val_fu_2652_p135;
wire   [7:0] val_fu_2652_p137;
wire   [7:0] val_fu_2652_p139;
wire   [7:0] val_fu_2652_p141;
wire   [7:0] val_fu_2652_p143;
wire   [7:0] val_fu_2652_p145;
wire   [7:0] val_fu_2652_p147;
wire   [7:0] val_fu_2652_p149;
wire   [7:0] val_fu_2652_p151;
wire   [7:0] val_fu_2652_p153;
wire   [7:0] val_fu_2652_p155;
wire   [7:0] val_fu_2652_p157;
wire   [7:0] val_fu_2652_p159;
wire   [7:0] val_fu_2652_p161;
wire   [7:0] val_fu_2652_p163;
wire   [7:0] val_fu_2652_p165;
wire   [7:0] val_fu_2652_p167;
wire   [7:0] val_fu_2652_p169;
wire   [7:0] val_fu_2652_p171;
wire   [7:0] val_fu_2652_p173;
wire   [7:0] val_fu_2652_p175;
wire   [7:0] val_fu_2652_p177;
wire   [7:0] val_fu_2652_p179;
wire   [7:0] val_fu_2652_p181;
wire   [7:0] val_fu_2652_p183;
wire   [7:0] val_fu_2652_p185;
wire   [7:0] val_fu_2652_p187;
wire   [7:0] val_fu_2652_p189;
wire   [7:0] val_fu_2652_p191;
wire   [7:0] val_fu_2652_p193;
wire   [7:0] val_fu_2652_p195;
wire   [7:0] val_fu_2652_p197;
wire   [7:0] val_fu_2652_p199;
wire   [7:0] val_fu_2652_p201;
wire   [7:0] val_fu_2652_p203;
wire   [7:0] val_fu_2652_p205;
wire   [7:0] val_fu_2652_p207;
wire   [7:0] val_fu_2652_p209;
wire   [7:0] val_fu_2652_p211;
wire   [7:0] val_fu_2652_p213;
wire   [7:0] val_fu_2652_p215;
wire   [7:0] val_fu_2652_p217;
wire   [7:0] val_fu_2652_p219;
wire   [7:0] val_fu_2652_p221;
wire   [7:0] val_fu_2652_p223;
wire   [7:0] val_fu_2652_p225;
wire   [7:0] val_fu_2652_p227;
wire   [7:0] val_fu_2652_p229;
wire   [7:0] val_fu_2652_p231;
wire   [7:0] val_fu_2652_p233;
wire   [7:0] val_fu_2652_p235;
wire   [7:0] val_fu_2652_p237;
wire   [7:0] val_fu_2652_p239;
wire   [7:0] val_fu_2652_p241;
wire   [7:0] val_fu_2652_p243;
wire   [7:0] val_fu_2652_p245;
wire   [7:0] val_fu_2652_p247;
wire   [7:0] val_fu_2652_p249;
wire   [7:0] val_fu_2652_p251;
wire   [7:0] val_fu_2652_p253;
wire   [7:0] val_fu_2652_p255;
wire  signed [7:0] val_fu_2652_p257;
wire  signed [7:0] val_fu_2652_p259;
wire  signed [7:0] val_fu_2652_p261;
wire  signed [7:0] val_fu_2652_p263;
wire  signed [7:0] val_fu_2652_p265;
wire  signed [7:0] val_fu_2652_p267;
wire  signed [7:0] val_fu_2652_p269;
wire  signed [7:0] val_fu_2652_p271;
wire  signed [7:0] val_fu_2652_p273;
wire  signed [7:0] val_fu_2652_p275;
wire  signed [7:0] val_fu_2652_p277;
wire  signed [7:0] val_fu_2652_p279;
wire  signed [7:0] val_fu_2652_p281;
wire  signed [7:0] val_fu_2652_p283;
wire  signed [7:0] val_fu_2652_p285;
wire  signed [7:0] val_fu_2652_p287;
wire  signed [7:0] val_fu_2652_p289;
wire  signed [7:0] val_fu_2652_p291;
wire  signed [7:0] val_fu_2652_p293;
wire  signed [7:0] val_fu_2652_p295;
wire  signed [7:0] val_fu_2652_p297;
wire  signed [7:0] val_fu_2652_p299;
wire  signed [7:0] val_fu_2652_p301;
wire  signed [7:0] val_fu_2652_p303;
wire  signed [7:0] val_fu_2652_p305;
wire  signed [7:0] val_fu_2652_p307;
wire  signed [7:0] val_fu_2652_p309;
wire  signed [7:0] val_fu_2652_p311;
wire  signed [7:0] val_fu_2652_p313;
wire  signed [7:0] val_fu_2652_p315;
wire  signed [7:0] val_fu_2652_p317;
wire  signed [7:0] val_fu_2652_p319;
wire  signed [7:0] val_fu_2652_p321;
wire  signed [7:0] val_fu_2652_p323;
wire  signed [7:0] val_fu_2652_p325;
wire  signed [7:0] val_fu_2652_p327;
wire  signed [7:0] val_fu_2652_p329;
wire  signed [7:0] val_fu_2652_p331;
wire  signed [7:0] val_fu_2652_p333;
wire  signed [7:0] val_fu_2652_p335;
wire  signed [7:0] val_fu_2652_p337;
wire  signed [7:0] val_fu_2652_p339;
wire  signed [7:0] val_fu_2652_p341;
wire  signed [7:0] val_fu_2652_p343;
wire  signed [7:0] val_fu_2652_p345;
wire  signed [7:0] val_fu_2652_p347;
wire  signed [7:0] val_fu_2652_p349;
wire  signed [7:0] val_fu_2652_p351;
wire  signed [7:0] val_fu_2652_p353;
wire  signed [7:0] val_fu_2652_p355;
wire  signed [7:0] val_fu_2652_p357;
wire  signed [7:0] val_fu_2652_p359;
wire  signed [7:0] val_fu_2652_p361;
wire  signed [7:0] val_fu_2652_p363;
wire  signed [7:0] val_fu_2652_p365;
wire  signed [7:0] val_fu_2652_p367;
wire  signed [7:0] val_fu_2652_p369;
wire  signed [7:0] val_fu_2652_p371;
wire  signed [7:0] val_fu_2652_p373;
wire  signed [7:0] val_fu_2652_p375;
wire  signed [7:0] val_fu_2652_p377;
wire  signed [7:0] val_fu_2652_p379;
wire  signed [7:0] val_fu_2652_p381;
wire  signed [7:0] val_fu_2652_p383;
wire  signed [7:0] val_fu_2652_p385;
wire  signed [7:0] val_fu_2652_p387;
wire  signed [7:0] val_fu_2652_p389;
wire  signed [7:0] val_fu_2652_p391;
wire  signed [7:0] val_fu_2652_p393;
wire  signed [7:0] val_fu_2652_p395;
wire  signed [7:0] val_fu_2652_p397;
wire  signed [7:0] val_fu_2652_p399;
wire  signed [7:0] val_fu_2652_p401;
wire  signed [7:0] val_fu_2652_p403;
wire  signed [7:0] val_fu_2652_p405;
wire  signed [7:0] val_fu_2652_p407;
wire  signed [7:0] val_fu_2652_p409;
wire  signed [7:0] val_fu_2652_p411;
wire  signed [7:0] val_fu_2652_p413;
wire  signed [7:0] val_fu_2652_p415;
wire  signed [7:0] val_fu_2652_p417;
wire  signed [7:0] val_fu_2652_p419;
wire  signed [7:0] val_fu_2652_p421;
wire  signed [7:0] val_fu_2652_p423;
wire  signed [7:0] val_fu_2652_p425;
wire  signed [7:0] val_fu_2652_p427;
wire  signed [7:0] val_fu_2652_p429;
wire  signed [7:0] val_fu_2652_p431;
wire  signed [7:0] val_fu_2652_p433;
wire  signed [7:0] val_fu_2652_p435;
wire  signed [7:0] val_fu_2652_p437;
wire  signed [7:0] val_fu_2652_p439;
wire  signed [7:0] val_fu_2652_p441;
wire  signed [7:0] val_fu_2652_p443;
wire  signed [7:0] val_fu_2652_p445;
wire  signed [7:0] val_fu_2652_p447;
wire  signed [7:0] val_fu_2652_p449;
wire  signed [7:0] val_fu_2652_p451;
wire  signed [7:0] val_fu_2652_p453;
wire  signed [7:0] val_fu_2652_p455;
wire  signed [7:0] val_fu_2652_p457;
wire  signed [7:0] val_fu_2652_p459;
wire  signed [7:0] val_fu_2652_p461;
wire  signed [7:0] val_fu_2652_p463;
wire  signed [7:0] val_fu_2652_p465;
wire  signed [7:0] val_fu_2652_p467;
wire  signed [7:0] val_fu_2652_p469;
wire  signed [7:0] val_fu_2652_p471;
wire  signed [7:0] val_fu_2652_p473;
wire  signed [7:0] val_fu_2652_p475;
wire  signed [7:0] val_fu_2652_p477;
wire  signed [7:0] val_fu_2652_p479;
wire  signed [7:0] val_fu_2652_p481;
wire  signed [7:0] val_fu_2652_p483;
wire  signed [7:0] val_fu_2652_p485;
wire  signed [7:0] val_fu_2652_p487;
wire  signed [7:0] val_fu_2652_p489;
wire  signed [7:0] val_fu_2652_p491;
wire  signed [7:0] val_fu_2652_p493;
wire  signed [7:0] val_fu_2652_p495;
wire  signed [7:0] val_fu_2652_p497;
wire  signed [7:0] val_fu_2652_p499;
wire  signed [7:0] val_fu_2652_p501;
wire  signed [7:0] val_fu_2652_p503;
wire  signed [7:0] val_fu_2652_p505;
wire  signed [7:0] val_fu_2652_p507;
wire  signed [7:0] val_fu_2652_p509;
wire  signed [7:0] val_fu_2652_p511;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 max_q1_fu_1066 = 8'd0;
#0 i_fu_1070 = 9'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) quantize_nf4_q2_6_sparsemux_513_8_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 8'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 8'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 8'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 8'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 8'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 8'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 8'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 8'h8 ),
    .din8_WIDTH( 8 ),
    .CASE9( 8'h9 ),
    .din9_WIDTH( 8 ),
    .CASE10( 8'hA ),
    .din10_WIDTH( 8 ),
    .CASE11( 8'hB ),
    .din11_WIDTH( 8 ),
    .CASE12( 8'hC ),
    .din12_WIDTH( 8 ),
    .CASE13( 8'hD ),
    .din13_WIDTH( 8 ),
    .CASE14( 8'hE ),
    .din14_WIDTH( 8 ),
    .CASE15( 8'hF ),
    .din15_WIDTH( 8 ),
    .CASE16( 8'h10 ),
    .din16_WIDTH( 8 ),
    .CASE17( 8'h11 ),
    .din17_WIDTH( 8 ),
    .CASE18( 8'h12 ),
    .din18_WIDTH( 8 ),
    .CASE19( 8'h13 ),
    .din19_WIDTH( 8 ),
    .CASE20( 8'h14 ),
    .din20_WIDTH( 8 ),
    .CASE21( 8'h15 ),
    .din21_WIDTH( 8 ),
    .CASE22( 8'h16 ),
    .din22_WIDTH( 8 ),
    .CASE23( 8'h17 ),
    .din23_WIDTH( 8 ),
    .CASE24( 8'h18 ),
    .din24_WIDTH( 8 ),
    .CASE25( 8'h19 ),
    .din25_WIDTH( 8 ),
    .CASE26( 8'h1A ),
    .din26_WIDTH( 8 ),
    .CASE27( 8'h1B ),
    .din27_WIDTH( 8 ),
    .CASE28( 8'h1C ),
    .din28_WIDTH( 8 ),
    .CASE29( 8'h1D ),
    .din29_WIDTH( 8 ),
    .CASE30( 8'h1E ),
    .din30_WIDTH( 8 ),
    .CASE31( 8'h1F ),
    .din31_WIDTH( 8 ),
    .CASE32( 8'h20 ),
    .din32_WIDTH( 8 ),
    .CASE33( 8'h21 ),
    .din33_WIDTH( 8 ),
    .CASE34( 8'h22 ),
    .din34_WIDTH( 8 ),
    .CASE35( 8'h23 ),
    .din35_WIDTH( 8 ),
    .CASE36( 8'h24 ),
    .din36_WIDTH( 8 ),
    .CASE37( 8'h25 ),
    .din37_WIDTH( 8 ),
    .CASE38( 8'h26 ),
    .din38_WIDTH( 8 ),
    .CASE39( 8'h27 ),
    .din39_WIDTH( 8 ),
    .CASE40( 8'h28 ),
    .din40_WIDTH( 8 ),
    .CASE41( 8'h29 ),
    .din41_WIDTH( 8 ),
    .CASE42( 8'h2A ),
    .din42_WIDTH( 8 ),
    .CASE43( 8'h2B ),
    .din43_WIDTH( 8 ),
    .CASE44( 8'h2C ),
    .din44_WIDTH( 8 ),
    .CASE45( 8'h2D ),
    .din45_WIDTH( 8 ),
    .CASE46( 8'h2E ),
    .din46_WIDTH( 8 ),
    .CASE47( 8'h2F ),
    .din47_WIDTH( 8 ),
    .CASE48( 8'h30 ),
    .din48_WIDTH( 8 ),
    .CASE49( 8'h31 ),
    .din49_WIDTH( 8 ),
    .CASE50( 8'h32 ),
    .din50_WIDTH( 8 ),
    .CASE51( 8'h33 ),
    .din51_WIDTH( 8 ),
    .CASE52( 8'h34 ),
    .din52_WIDTH( 8 ),
    .CASE53( 8'h35 ),
    .din53_WIDTH( 8 ),
    .CASE54( 8'h36 ),
    .din54_WIDTH( 8 ),
    .CASE55( 8'h37 ),
    .din55_WIDTH( 8 ),
    .CASE56( 8'h38 ),
    .din56_WIDTH( 8 ),
    .CASE57( 8'h39 ),
    .din57_WIDTH( 8 ),
    .CASE58( 8'h3A ),
    .din58_WIDTH( 8 ),
    .CASE59( 8'h3B ),
    .din59_WIDTH( 8 ),
    .CASE60( 8'h3C ),
    .din60_WIDTH( 8 ),
    .CASE61( 8'h3D ),
    .din61_WIDTH( 8 ),
    .CASE62( 8'h3E ),
    .din62_WIDTH( 8 ),
    .CASE63( 8'h3F ),
    .din63_WIDTH( 8 ),
    .CASE64( 8'h40 ),
    .din64_WIDTH( 8 ),
    .CASE65( 8'h41 ),
    .din65_WIDTH( 8 ),
    .CASE66( 8'h42 ),
    .din66_WIDTH( 8 ),
    .CASE67( 8'h43 ),
    .din67_WIDTH( 8 ),
    .CASE68( 8'h44 ),
    .din68_WIDTH( 8 ),
    .CASE69( 8'h45 ),
    .din69_WIDTH( 8 ),
    .CASE70( 8'h46 ),
    .din70_WIDTH( 8 ),
    .CASE71( 8'h47 ),
    .din71_WIDTH( 8 ),
    .CASE72( 8'h48 ),
    .din72_WIDTH( 8 ),
    .CASE73( 8'h49 ),
    .din73_WIDTH( 8 ),
    .CASE74( 8'h4A ),
    .din74_WIDTH( 8 ),
    .CASE75( 8'h4B ),
    .din75_WIDTH( 8 ),
    .CASE76( 8'h4C ),
    .din76_WIDTH( 8 ),
    .CASE77( 8'h4D ),
    .din77_WIDTH( 8 ),
    .CASE78( 8'h4E ),
    .din78_WIDTH( 8 ),
    .CASE79( 8'h4F ),
    .din79_WIDTH( 8 ),
    .CASE80( 8'h50 ),
    .din80_WIDTH( 8 ),
    .CASE81( 8'h51 ),
    .din81_WIDTH( 8 ),
    .CASE82( 8'h52 ),
    .din82_WIDTH( 8 ),
    .CASE83( 8'h53 ),
    .din83_WIDTH( 8 ),
    .CASE84( 8'h54 ),
    .din84_WIDTH( 8 ),
    .CASE85( 8'h55 ),
    .din85_WIDTH( 8 ),
    .CASE86( 8'h56 ),
    .din86_WIDTH( 8 ),
    .CASE87( 8'h57 ),
    .din87_WIDTH( 8 ),
    .CASE88( 8'h58 ),
    .din88_WIDTH( 8 ),
    .CASE89( 8'h59 ),
    .din89_WIDTH( 8 ),
    .CASE90( 8'h5A ),
    .din90_WIDTH( 8 ),
    .CASE91( 8'h5B ),
    .din91_WIDTH( 8 ),
    .CASE92( 8'h5C ),
    .din92_WIDTH( 8 ),
    .CASE93( 8'h5D ),
    .din93_WIDTH( 8 ),
    .CASE94( 8'h5E ),
    .din94_WIDTH( 8 ),
    .CASE95( 8'h5F ),
    .din95_WIDTH( 8 ),
    .CASE96( 8'h60 ),
    .din96_WIDTH( 8 ),
    .CASE97( 8'h61 ),
    .din97_WIDTH( 8 ),
    .CASE98( 8'h62 ),
    .din98_WIDTH( 8 ),
    .CASE99( 8'h63 ),
    .din99_WIDTH( 8 ),
    .CASE100( 8'h64 ),
    .din100_WIDTH( 8 ),
    .CASE101( 8'h65 ),
    .din101_WIDTH( 8 ),
    .CASE102( 8'h66 ),
    .din102_WIDTH( 8 ),
    .CASE103( 8'h67 ),
    .din103_WIDTH( 8 ),
    .CASE104( 8'h68 ),
    .din104_WIDTH( 8 ),
    .CASE105( 8'h69 ),
    .din105_WIDTH( 8 ),
    .CASE106( 8'h6A ),
    .din106_WIDTH( 8 ),
    .CASE107( 8'h6B ),
    .din107_WIDTH( 8 ),
    .CASE108( 8'h6C ),
    .din108_WIDTH( 8 ),
    .CASE109( 8'h6D ),
    .din109_WIDTH( 8 ),
    .CASE110( 8'h6E ),
    .din110_WIDTH( 8 ),
    .CASE111( 8'h6F ),
    .din111_WIDTH( 8 ),
    .CASE112( 8'h70 ),
    .din112_WIDTH( 8 ),
    .CASE113( 8'h71 ),
    .din113_WIDTH( 8 ),
    .CASE114( 8'h72 ),
    .din114_WIDTH( 8 ),
    .CASE115( 8'h73 ),
    .din115_WIDTH( 8 ),
    .CASE116( 8'h74 ),
    .din116_WIDTH( 8 ),
    .CASE117( 8'h75 ),
    .din117_WIDTH( 8 ),
    .CASE118( 8'h76 ),
    .din118_WIDTH( 8 ),
    .CASE119( 8'h77 ),
    .din119_WIDTH( 8 ),
    .CASE120( 8'h78 ),
    .din120_WIDTH( 8 ),
    .CASE121( 8'h79 ),
    .din121_WIDTH( 8 ),
    .CASE122( 8'h7A ),
    .din122_WIDTH( 8 ),
    .CASE123( 8'h7B ),
    .din123_WIDTH( 8 ),
    .CASE124( 8'h7C ),
    .din124_WIDTH( 8 ),
    .CASE125( 8'h7D ),
    .din125_WIDTH( 8 ),
    .CASE126( 8'h7E ),
    .din126_WIDTH( 8 ),
    .CASE127( 8'h7F ),
    .din127_WIDTH( 8 ),
    .CASE128( 8'h80 ),
    .din128_WIDTH( 8 ),
    .CASE129( 8'h81 ),
    .din129_WIDTH( 8 ),
    .CASE130( 8'h82 ),
    .din130_WIDTH( 8 ),
    .CASE131( 8'h83 ),
    .din131_WIDTH( 8 ),
    .CASE132( 8'h84 ),
    .din132_WIDTH( 8 ),
    .CASE133( 8'h85 ),
    .din133_WIDTH( 8 ),
    .CASE134( 8'h86 ),
    .din134_WIDTH( 8 ),
    .CASE135( 8'h87 ),
    .din135_WIDTH( 8 ),
    .CASE136( 8'h88 ),
    .din136_WIDTH( 8 ),
    .CASE137( 8'h89 ),
    .din137_WIDTH( 8 ),
    .CASE138( 8'h8A ),
    .din138_WIDTH( 8 ),
    .CASE139( 8'h8B ),
    .din139_WIDTH( 8 ),
    .CASE140( 8'h8C ),
    .din140_WIDTH( 8 ),
    .CASE141( 8'h8D ),
    .din141_WIDTH( 8 ),
    .CASE142( 8'h8E ),
    .din142_WIDTH( 8 ),
    .CASE143( 8'h8F ),
    .din143_WIDTH( 8 ),
    .CASE144( 8'h90 ),
    .din144_WIDTH( 8 ),
    .CASE145( 8'h91 ),
    .din145_WIDTH( 8 ),
    .CASE146( 8'h92 ),
    .din146_WIDTH( 8 ),
    .CASE147( 8'h93 ),
    .din147_WIDTH( 8 ),
    .CASE148( 8'h94 ),
    .din148_WIDTH( 8 ),
    .CASE149( 8'h95 ),
    .din149_WIDTH( 8 ),
    .CASE150( 8'h96 ),
    .din150_WIDTH( 8 ),
    .CASE151( 8'h97 ),
    .din151_WIDTH( 8 ),
    .CASE152( 8'h98 ),
    .din152_WIDTH( 8 ),
    .CASE153( 8'h99 ),
    .din153_WIDTH( 8 ),
    .CASE154( 8'h9A ),
    .din154_WIDTH( 8 ),
    .CASE155( 8'h9B ),
    .din155_WIDTH( 8 ),
    .CASE156( 8'h9C ),
    .din156_WIDTH( 8 ),
    .CASE157( 8'h9D ),
    .din157_WIDTH( 8 ),
    .CASE158( 8'h9E ),
    .din158_WIDTH( 8 ),
    .CASE159( 8'h9F ),
    .din159_WIDTH( 8 ),
    .CASE160( 8'hA0 ),
    .din160_WIDTH( 8 ),
    .CASE161( 8'hA1 ),
    .din161_WIDTH( 8 ),
    .CASE162( 8'hA2 ),
    .din162_WIDTH( 8 ),
    .CASE163( 8'hA3 ),
    .din163_WIDTH( 8 ),
    .CASE164( 8'hA4 ),
    .din164_WIDTH( 8 ),
    .CASE165( 8'hA5 ),
    .din165_WIDTH( 8 ),
    .CASE166( 8'hA6 ),
    .din166_WIDTH( 8 ),
    .CASE167( 8'hA7 ),
    .din167_WIDTH( 8 ),
    .CASE168( 8'hA8 ),
    .din168_WIDTH( 8 ),
    .CASE169( 8'hA9 ),
    .din169_WIDTH( 8 ),
    .CASE170( 8'hAA ),
    .din170_WIDTH( 8 ),
    .CASE171( 8'hAB ),
    .din171_WIDTH( 8 ),
    .CASE172( 8'hAC ),
    .din172_WIDTH( 8 ),
    .CASE173( 8'hAD ),
    .din173_WIDTH( 8 ),
    .CASE174( 8'hAE ),
    .din174_WIDTH( 8 ),
    .CASE175( 8'hAF ),
    .din175_WIDTH( 8 ),
    .CASE176( 8'hB0 ),
    .din176_WIDTH( 8 ),
    .CASE177( 8'hB1 ),
    .din177_WIDTH( 8 ),
    .CASE178( 8'hB2 ),
    .din178_WIDTH( 8 ),
    .CASE179( 8'hB3 ),
    .din179_WIDTH( 8 ),
    .CASE180( 8'hB4 ),
    .din180_WIDTH( 8 ),
    .CASE181( 8'hB5 ),
    .din181_WIDTH( 8 ),
    .CASE182( 8'hB6 ),
    .din182_WIDTH( 8 ),
    .CASE183( 8'hB7 ),
    .din183_WIDTH( 8 ),
    .CASE184( 8'hB8 ),
    .din184_WIDTH( 8 ),
    .CASE185( 8'hB9 ),
    .din185_WIDTH( 8 ),
    .CASE186( 8'hBA ),
    .din186_WIDTH( 8 ),
    .CASE187( 8'hBB ),
    .din187_WIDTH( 8 ),
    .CASE188( 8'hBC ),
    .din188_WIDTH( 8 ),
    .CASE189( 8'hBD ),
    .din189_WIDTH( 8 ),
    .CASE190( 8'hBE ),
    .din190_WIDTH( 8 ),
    .CASE191( 8'hBF ),
    .din191_WIDTH( 8 ),
    .CASE192( 8'hC0 ),
    .din192_WIDTH( 8 ),
    .CASE193( 8'hC1 ),
    .din193_WIDTH( 8 ),
    .CASE194( 8'hC2 ),
    .din194_WIDTH( 8 ),
    .CASE195( 8'hC3 ),
    .din195_WIDTH( 8 ),
    .CASE196( 8'hC4 ),
    .din196_WIDTH( 8 ),
    .CASE197( 8'hC5 ),
    .din197_WIDTH( 8 ),
    .CASE198( 8'hC6 ),
    .din198_WIDTH( 8 ),
    .CASE199( 8'hC7 ),
    .din199_WIDTH( 8 ),
    .CASE200( 8'hC8 ),
    .din200_WIDTH( 8 ),
    .CASE201( 8'hC9 ),
    .din201_WIDTH( 8 ),
    .CASE202( 8'hCA ),
    .din202_WIDTH( 8 ),
    .CASE203( 8'hCB ),
    .din203_WIDTH( 8 ),
    .CASE204( 8'hCC ),
    .din204_WIDTH( 8 ),
    .CASE205( 8'hCD ),
    .din205_WIDTH( 8 ),
    .CASE206( 8'hCE ),
    .din206_WIDTH( 8 ),
    .CASE207( 8'hCF ),
    .din207_WIDTH( 8 ),
    .CASE208( 8'hD0 ),
    .din208_WIDTH( 8 ),
    .CASE209( 8'hD1 ),
    .din209_WIDTH( 8 ),
    .CASE210( 8'hD2 ),
    .din210_WIDTH( 8 ),
    .CASE211( 8'hD3 ),
    .din211_WIDTH( 8 ),
    .CASE212( 8'hD4 ),
    .din212_WIDTH( 8 ),
    .CASE213( 8'hD5 ),
    .din213_WIDTH( 8 ),
    .CASE214( 8'hD6 ),
    .din214_WIDTH( 8 ),
    .CASE215( 8'hD7 ),
    .din215_WIDTH( 8 ),
    .CASE216( 8'hD8 ),
    .din216_WIDTH( 8 ),
    .CASE217( 8'hD9 ),
    .din217_WIDTH( 8 ),
    .CASE218( 8'hDA ),
    .din218_WIDTH( 8 ),
    .CASE219( 8'hDB ),
    .din219_WIDTH( 8 ),
    .CASE220( 8'hDC ),
    .din220_WIDTH( 8 ),
    .CASE221( 8'hDD ),
    .din221_WIDTH( 8 ),
    .CASE222( 8'hDE ),
    .din222_WIDTH( 8 ),
    .CASE223( 8'hDF ),
    .din223_WIDTH( 8 ),
    .CASE224( 8'hE0 ),
    .din224_WIDTH( 8 ),
    .CASE225( 8'hE1 ),
    .din225_WIDTH( 8 ),
    .CASE226( 8'hE2 ),
    .din226_WIDTH( 8 ),
    .CASE227( 8'hE3 ),
    .din227_WIDTH( 8 ),
    .CASE228( 8'hE4 ),
    .din228_WIDTH( 8 ),
    .CASE229( 8'hE5 ),
    .din229_WIDTH( 8 ),
    .CASE230( 8'hE6 ),
    .din230_WIDTH( 8 ),
    .CASE231( 8'hE7 ),
    .din231_WIDTH( 8 ),
    .CASE232( 8'hE8 ),
    .din232_WIDTH( 8 ),
    .CASE233( 8'hE9 ),
    .din233_WIDTH( 8 ),
    .CASE234( 8'hEA ),
    .din234_WIDTH( 8 ),
    .CASE235( 8'hEB ),
    .din235_WIDTH( 8 ),
    .CASE236( 8'hEC ),
    .din236_WIDTH( 8 ),
    .CASE237( 8'hED ),
    .din237_WIDTH( 8 ),
    .CASE238( 8'hEE ),
    .din238_WIDTH( 8 ),
    .CASE239( 8'hEF ),
    .din239_WIDTH( 8 ),
    .CASE240( 8'hF0 ),
    .din240_WIDTH( 8 ),
    .CASE241( 8'hF1 ),
    .din241_WIDTH( 8 ),
    .CASE242( 8'hF2 ),
    .din242_WIDTH( 8 ),
    .CASE243( 8'hF3 ),
    .din243_WIDTH( 8 ),
    .CASE244( 8'hF4 ),
    .din244_WIDTH( 8 ),
    .CASE245( 8'hF5 ),
    .din245_WIDTH( 8 ),
    .CASE246( 8'hF6 ),
    .din246_WIDTH( 8 ),
    .CASE247( 8'hF7 ),
    .din247_WIDTH( 8 ),
    .CASE248( 8'hF8 ),
    .din248_WIDTH( 8 ),
    .CASE249( 8'hF9 ),
    .din249_WIDTH( 8 ),
    .CASE250( 8'hFA ),
    .din250_WIDTH( 8 ),
    .CASE251( 8'hFB ),
    .din251_WIDTH( 8 ),
    .CASE252( 8'hFC ),
    .din252_WIDTH( 8 ),
    .CASE253( 8'hFD ),
    .din253_WIDTH( 8 ),
    .CASE254( 8'hFE ),
    .din254_WIDTH( 8 ),
    .CASE255( 8'hFF ),
    .din255_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
sparsemux_513_8_8_1_1_U4(
    .din0(q1_constants),
    .din1(q1_constants_1),
    .din2(q1_constants_2),
    .din3(q1_constants_3),
    .din4(q1_constants_4),
    .din5(q1_constants_5),
    .din6(q1_constants_6),
    .din7(q1_constants_7),
    .din8(q1_constants_8),
    .din9(q1_constants_9),
    .din10(q1_constants_10),
    .din11(q1_constants_11),
    .din12(q1_constants_12),
    .din13(q1_constants_13),
    .din14(q1_constants_14),
    .din15(q1_constants_15),
    .din16(q1_constants_16),
    .din17(q1_constants_17),
    .din18(q1_constants_18),
    .din19(q1_constants_19),
    .din20(q1_constants_20),
    .din21(q1_constants_21),
    .din22(q1_constants_22),
    .din23(q1_constants_23),
    .din24(q1_constants_24),
    .din25(q1_constants_25),
    .din26(q1_constants_26),
    .din27(q1_constants_27),
    .din28(q1_constants_28),
    .din29(q1_constants_29),
    .din30(q1_constants_30),
    .din31(q1_constants_31),
    .din32(q1_constants_32),
    .din33(q1_constants_33),
    .din34(q1_constants_34),
    .din35(q1_constants_35),
    .din36(q1_constants_36),
    .din37(q1_constants_37),
    .din38(q1_constants_38),
    .din39(q1_constants_39),
    .din40(q1_constants_40),
    .din41(q1_constants_41),
    .din42(q1_constants_42),
    .din43(q1_constants_43),
    .din44(q1_constants_44),
    .din45(q1_constants_45),
    .din46(q1_constants_46),
    .din47(q1_constants_47),
    .din48(q1_constants_48),
    .din49(q1_constants_49),
    .din50(q1_constants_50),
    .din51(q1_constants_51),
    .din52(q1_constants_52),
    .din53(q1_constants_53),
    .din54(q1_constants_54),
    .din55(q1_constants_55),
    .din56(q1_constants_56),
    .din57(q1_constants_57),
    .din58(q1_constants_58),
    .din59(q1_constants_59),
    .din60(q1_constants_60),
    .din61(q1_constants_61),
    .din62(q1_constants_62),
    .din63(q1_constants_63),
    .din64(q1_constants_64),
    .din65(q1_constants_65),
    .din66(q1_constants_66),
    .din67(q1_constants_67),
    .din68(q1_constants_68),
    .din69(q1_constants_69),
    .din70(q1_constants_70),
    .din71(q1_constants_71),
    .din72(q1_constants_72),
    .din73(q1_constants_73),
    .din74(q1_constants_74),
    .din75(q1_constants_75),
    .din76(q1_constants_76),
    .din77(q1_constants_77),
    .din78(q1_constants_78),
    .din79(q1_constants_79),
    .din80(q1_constants_80),
    .din81(q1_constants_81),
    .din82(q1_constants_82),
    .din83(q1_constants_83),
    .din84(q1_constants_84),
    .din85(q1_constants_85),
    .din86(q1_constants_86),
    .din87(q1_constants_87),
    .din88(q1_constants_88),
    .din89(q1_constants_89),
    .din90(q1_constants_90),
    .din91(q1_constants_91),
    .din92(q1_constants_92),
    .din93(q1_constants_93),
    .din94(q1_constants_94),
    .din95(q1_constants_95),
    .din96(q1_constants_96),
    .din97(q1_constants_97),
    .din98(q1_constants_98),
    .din99(q1_constants_99),
    .din100(q1_constants_100),
    .din101(q1_constants_101),
    .din102(q1_constants_102),
    .din103(q1_constants_103),
    .din104(q1_constants_104),
    .din105(q1_constants_105),
    .din106(q1_constants_106),
    .din107(q1_constants_107),
    .din108(q1_constants_108),
    .din109(q1_constants_109),
    .din110(q1_constants_110),
    .din111(q1_constants_111),
    .din112(q1_constants_112),
    .din113(q1_constants_113),
    .din114(q1_constants_114),
    .din115(q1_constants_115),
    .din116(q1_constants_116),
    .din117(q1_constants_117),
    .din118(q1_constants_118),
    .din119(q1_constants_119),
    .din120(q1_constants_120),
    .din121(q1_constants_121),
    .din122(q1_constants_122),
    .din123(q1_constants_123),
    .din124(q1_constants_124),
    .din125(q1_constants_125),
    .din126(q1_constants_126),
    .din127(q1_constants_127),
    .din128(q1_constants_128),
    .din129(q1_constants_129),
    .din130(q1_constants_130),
    .din131(q1_constants_131),
    .din132(q1_constants_132),
    .din133(q1_constants_133),
    .din134(q1_constants_134),
    .din135(q1_constants_135),
    .din136(q1_constants_136),
    .din137(q1_constants_137),
    .din138(q1_constants_138),
    .din139(q1_constants_139),
    .din140(q1_constants_140),
    .din141(q1_constants_141),
    .din142(q1_constants_142),
    .din143(q1_constants_143),
    .din144(q1_constants_144),
    .din145(q1_constants_145),
    .din146(q1_constants_146),
    .din147(q1_constants_147),
    .din148(q1_constants_148),
    .din149(q1_constants_149),
    .din150(q1_constants_150),
    .din151(q1_constants_151),
    .din152(q1_constants_152),
    .din153(q1_constants_153),
    .din154(q1_constants_154),
    .din155(q1_constants_155),
    .din156(q1_constants_156),
    .din157(q1_constants_157),
    .din158(q1_constants_158),
    .din159(q1_constants_159),
    .din160(q1_constants_160),
    .din161(q1_constants_161),
    .din162(q1_constants_162),
    .din163(q1_constants_163),
    .din164(q1_constants_164),
    .din165(q1_constants_165),
    .din166(q1_constants_166),
    .din167(q1_constants_167),
    .din168(q1_constants_168),
    .din169(q1_constants_169),
    .din170(q1_constants_170),
    .din171(q1_constants_171),
    .din172(q1_constants_172),
    .din173(q1_constants_173),
    .din174(q1_constants_174),
    .din175(q1_constants_175),
    .din176(q1_constants_176),
    .din177(q1_constants_177),
    .din178(q1_constants_178),
    .din179(q1_constants_179),
    .din180(q1_constants_180),
    .din181(q1_constants_181),
    .din182(q1_constants_182),
    .din183(q1_constants_183),
    .din184(q1_constants_184),
    .din185(q1_constants_185),
    .din186(q1_constants_186),
    .din187(q1_constants_187),
    .din188(q1_constants_188),
    .din189(q1_constants_189),
    .din190(q1_constants_190),
    .din191(q1_constants_191),
    .din192(q1_constants_192),
    .din193(q1_constants_193),
    .din194(q1_constants_194),
    .din195(q1_constants_195),
    .din196(q1_constants_196),
    .din197(q1_constants_197),
    .din198(q1_constants_198),
    .din199(q1_constants_199),
    .din200(q1_constants_200),
    .din201(q1_constants_201),
    .din202(q1_constants_202),
    .din203(q1_constants_203),
    .din204(q1_constants_204),
    .din205(q1_constants_205),
    .din206(q1_constants_206),
    .din207(q1_constants_207),
    .din208(q1_constants_208),
    .din209(q1_constants_209),
    .din210(q1_constants_210),
    .din211(q1_constants_211),
    .din212(q1_constants_212),
    .din213(q1_constants_213),
    .din214(q1_constants_214),
    .din215(q1_constants_215),
    .din216(q1_constants_216),
    .din217(q1_constants_217),
    .din218(q1_constants_218),
    .din219(q1_constants_219),
    .din220(q1_constants_220),
    .din221(q1_constants_221),
    .din222(q1_constants_222),
    .din223(q1_constants_223),
    .din224(q1_constants_224),
    .din225(q1_constants_225),
    .din226(q1_constants_226),
    .din227(q1_constants_227),
    .din228(q1_constants_228),
    .din229(q1_constants_229),
    .din230(q1_constants_230),
    .din231(q1_constants_231),
    .din232(q1_constants_232),
    .din233(q1_constants_233),
    .din234(q1_constants_234),
    .din235(q1_constants_235),
    .din236(q1_constants_236),
    .din237(q1_constants_237),
    .din238(q1_constants_238),
    .din239(q1_constants_239),
    .din240(q1_constants_240),
    .din241(q1_constants_241),
    .din242(q1_constants_242),
    .din243(q1_constants_243),
    .din244(q1_constants_244),
    .din245(q1_constants_245),
    .din246(q1_constants_246),
    .din247(q1_constants_247),
    .din248(q1_constants_248),
    .din249(q1_constants_249),
    .din250(q1_constants_250),
    .din251(q1_constants_251),
    .din252(q1_constants_252),
    .din253(q1_constants_253),
    .din254(q1_constants_254),
    .din255(q1_constants_255),
    .def(val_fu_2652_p513),
    .sel(val_fu_2652_p514),
    .dout(val_fu_2652_p515)
);

quantize_nf4_q2_6_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln114_fu_2636_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_1070 <= add_ln114_fu_2642_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_1070 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_q1_fu_1066 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_q1_fu_1066 <= max_q1_1_fu_3719_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        abs_q_reg_3753 <= abs_q_fu_3698_p3;
    end
end

always @ (*) begin
    if (((icmp_ln114_fu_2636_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_1070;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln114_fu_2636_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_q1_out_ap_vld = 1'b1;
    end else begin
        max_q1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_q_fu_3698_p3 = ((tmp_1_fu_3684_p3[0:0] == 1'b1) ? sub_ln24_fu_3692_p2 : val_fu_2652_p515);

assign add_ln114_fu_2642_p2 = (ap_sig_allocacmp_i_1 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln114_fu_2636_p2 = ((ap_sig_allocacmp_i_1 == empty) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_3714_p2 = (($signed(abs_q_reg_3753) > $signed(max_q1_fu_1066)) ? 1'b1 : 1'b0);

assign max_q1_1_fu_3719_p3 = ((icmp_ln117_fu_3714_p2[0:0] == 1'b1) ? abs_q_reg_3753 : max_q1_fu_1066);

assign max_q1_out = max_q1_fu_1066;

assign sub_ln24_fu_3692_p2 = (8'd0 - val_fu_2652_p515);

assign tmp_1_fu_3684_p3 = val_fu_2652_p515[32'd7];

assign val_fu_2652_p513 = 'bx;

assign val_fu_2652_p514 = ap_sig_allocacmp_i_1[7:0];

endmodule //quantize_nf4_q2_6_quantize_nf4_q2_6_Pipeline_VITIS_LOOP_114_5
